import type {Line} from '../types';

// Only recognizes the padding generated by the retired story expander.
const atmosphere=/이\(가\) (?:한 박자 늦게 흔들렸다|방금 전보다 또렷해졌다|말 사이의 빈칸을 천천히 채웠다|다음 대답을 기다리듯 잠잠해졌다|서로 다른 표정을 한 화면에 묶었다|조금 전의 긴장을 부드럽게 흩뜨렸다)\.$/;
const summary=/에서 말로만 남아 있던 갈등이 ‘[^’]+’이라는 행동으로 바뀌었다\.$/;
const isPadding=(line:Line)=>line.speaker==='narrator'&&atmosphere.test(line.text);
export const hasLegacyPadding=(lines:Line[])=>lines.some(isPadding);

export function cleanLegacyLines(lines:Line[],cursor=0):{lines:Line[];cursor:number}{
 const kept:Line[]=[];
 let nextCursor=0;
 for(let i=0;i<lines.length;i++){
  // Each padding line was followed by one generated thought or reply.
  if(isPadding(lines[i])){i++;continue;}
  if(lines[i].speaker==='narrator'&&summary.test(lines[i].text))continue;
  kept.push(lines[i]);
  if(i<cursor)nextCursor++;
 }
 return {lines:kept,cursor:nextCursor};
}
