import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronRight,Heart,MapPin,Search,Shield,Target,X,Zap} from 'lucide-react';
import {bondEpisodes,caseFiles,extraCharacters,schoolById,schoolCharacters,type ExtraId,type SchoolLine} from './data/classroomMystery';
import {locationById} from './data/characters';
import {activeCase,addSequence,beginTrial,bondAvailable,bondRequirement,bondLines,caseAvailable,caseLines,clearSequence,collectEvidence,continueBond,continueCase,explainMotive,openCase,rebut,retryTrial,selectBondChoice,solvedCases,submitSequence,vote,type ClassroomState} from './engine/classroomMystery';
import {SchoolPortrait} from './SchoolPortrait';
import './classroom.css';

type Props={state:ClassroomState;chapter:number;name:string;canVisit:boolean;onChange:(state:ClassroomState)=>void;onBondStart:(id:ExtraId)=>void;onClose:()=>void};
function Speaker({line,name}:{line:SchoolLine;name:string}){
 const speaker=line.speaker==='player'?name:line.speaker==='narrator'?'':line.speaker==='alter'?'ALTER EGO':schoolById[line.speaker].name;
 return <div className={`classroom-line ${line.speaker==='narrator'?'inner-voice':''}`}><b>{speaker}</b><p>{line.text.replaceAll('{name}',name)}</p></div>;
}
export function ClassroomMystery({state,chapter,name,canVisit,onChange,onBondStart,onClose}:Props){
 const overlay=useRef<HTMLElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';overlay.current?.querySelector('button')?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
 const [claim,setClaim]=useState<number|null>(null),[bullet,setBullet]=useState<string|null>(null),[inspection,setInspection]=useState<string|null>(null),[hint,setHint]=useState(false),[ending,setEnding]=useState<ExtraId|null>(null);
 const c=activeCase(state),p=c?state.cases[c.id]:null,a=state.active;
 useEffect(()=>{setClaim(null);setBullet(null);setHint(false);setInspection(null);overlay.current?.scrollTo(0,0);},[c?.id,p?.phase,p?.round,a?.kind]);
 useEffect(()=>{if(!inspection)return;const previous=document.activeElement as HTMLElement|null;overlay.current?.querySelector<HTMLButtonElement>('.inspection-close')?.focus();return()=>previous?.focus();},[inspection]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();if(inspection)setInspection(null);else onClose();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onClose,inspection]);
 const back=()=>{if(a?.kind==='bond'){onClose();return;}setEnding(null);onChange({...state,active:null});};
 const next=(value:ClassroomState)=>onChange(value);
 const line=a?.kind==='bond'?bondLines(state)[a.line]:p?caseLines(state)[p.line]:undefined;
 const actor=line&&line.speaker!=='player'&&line.speaker!=='narrator'&&line.speaker!=='alter'?line.speaker:undefined;
 const inspected=c?.evidence.find(e=>e.id===inspection);
 const debate=c&&p?c.debates[p.round]:null;
 const canHint=state.bonds.juhan.trust>=20||state.bonds.minhyuk.trust>=20;
 return <section ref={overlay} onKeyDown={event=>{if(event.key!=='Tab')return;const buttons=Array.from((overlay.current?.querySelector('.evidence-inspection')??overlay.current)?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')??[]).filter(button=>button.getClientRects().length>0);if(!buttons.length)return;if(event.shiftKey&&document.activeElement===buttons[0]){event.preventDefault();buttons.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===buttons.at(-1)){event.preventDefault();buttons[0].focus();}}} className="classroom-overlay" role="dialog" aria-modal="true" aria-label="1반 학급재판과 새 인물 이야기">
  <div className="classroom-backdrop"/><header className="classroom-header"><button onClick={back} aria-label="사건 수첩으로"><ArrowLeft size={19}/></button><div><small>RE:ACTION / LOVE × CLASS TRIAL</small><b>{a?.kind==='bond'?bondEpisodes[a.id][a.episode].title:c?c.title:'우리 반의 다른 페이지'}</b></div><button onClick={onClose} aria-label="사건 수첩 닫기"><X size={20}/></button></header>
  {!a&&!ending&&<div className="classroom-hub">
   <div className="classroom-lead"><span className="trial-label">INVESTIGATION / CHAPTER {String(chapter).padStart(2,'0')}</span><h1>좋아하는 마음에도,<br/><em>증거가 필요할까?</em></h1><p>이름 하나가 지워진 영상, 기록에서 사라진 반장, 얼굴을 빌린 협박. 여덟 명의 동급생과 사실을 찾고, 그 뒤에 남은 마음을 직접 들어 보자.</p><div className="classroom-summary"><Search size={17}/>해결한 사건 {solvedCases(state)} / {caseFiles.length}<span>모든 인물의 일상과 연애는 이어집니다.</span></div></div>
   <div className="classroom-cases">{caseFiles.map(file=>{const progress=state.cases[file.id],available=caseAvailable(state,file.id,chapter);return <button key={file.id} disabled={!available} onClick={()=>next(openCase(state,file.id,chapter))}><small>CASE 0{file.number} / {progress.phase==='solved'?'RESOLVED':available?'OPEN':'LOCKED'}</small><h2>{file.title}</h2><p>{file.subtitle}</p><span>{progress.phase==='solved'?'사건의 결론 다시 보기':available?progress.phase==='opening'?'사건 시작하기':'조사 이어가기':`메인 ${file.chapter}장 · 이전 사건 해결 후`}<ChevronRight size={16}/></span></button>;})}</div>
   <div className="classroom-contact-heading"><Heart size={18}/><h2>방과 후, 사건 밖의 약속</h2></div>
   <div className="classroom-contacts">{extraCharacters.map(person=>{const bond=state.bonds[person.id],required=bondRequirement(state,person.id),episode=bondEpisodes[person.id][bond.visits],available=canVisit&&bondAvailable(state,person.id,chapter);return <article key={person.id}><SchoolPortrait id={person.id}/><div><small>{person.role}</small><h2>{person.name}</h2><p>{person.quote}</p><span>호감 {bond.affection} · 신뢰 {bond.trust} · 개인 이야기 {bond.visits}/4</span>{bond.ending?<button onClick={()=>setEnding(person.id)}><BookOpen size={15}/>두 사람의 결말 다시 보기</button>:<button disabled={!available} onClick={()=>onBondStart(person.id)}><Heart size={15}/>{available?`${episode.title} · 행동 1`:episode&&chapter<episode.chapter?`${episode.chapter}장 이후 다음 약속`:required&&state.cases[required].phase!=='solved'?`${caseFiles.find(c=>c.id===required)?.title} 해결 후 약속`:'방과 후 행동이 있을 때 만나기'}</button>}</div></article>;})}</div>
   <aside className="alter-terminal"><div className="alter-avatar">AE<span>ONLINE</span></div><p><b>ALTER EGO</b> 나는 주한이 만든 로컬 분석 AI야. 허락된 파일의 차이와 기록을 확인할 수 있어. 사람의 마음은 본인에게 물어봐 줘.</p></aside>
  </div>}
  {ending&&<div className="classroom-ending"><SchoolPortrait id={ending}/><span className="trial-label">{state.bonds[ending].ending==='true'?'TRUE ROMANCE':state.bonds[ending].ending==='friend'?'FRIENDSHIP':'DISTANCE'} / MEMORY</span><h1>{ending==='juhan'?'원본의 이름':'규칙 밖의 약속'}</h1>{state.bonds[ending].ending==='true'?<><p>{ending==='juhan'?`주한은 발표가 끝난 뒤 노트북을 닫고 ${name}의 손을 잡았다. 떨리는 날에도 직접 말하겠다는 약속은 자동 저장할 수 없었다. 그래서 둘은 다음 날도 만나기로 했다.`:`민혁의 일정표에 반장 업무가 아닌 약속이 적혔다. ${name}와 함께 정한 장소와 시간이었다. 민혁은 완장을 벗고, 반 전체가 아닌 한 사람에게 웃었다.`}</p><blockquote>{ending==='juhan'?'“네가 기다려 준 사람은 내가 만든 AI가 아니라 나였어. 좋아해.”':'“좋아하는 마음은 명령문으로 쓰지 않을게. 대신 내일도 직접 물어볼게.”'}</blockquote></>:state.bonds[ending].ending==='friend'?<p>솔직한 대답을 주고받은 두 사람은 친구로 남았다. 지금의 마음을 거짓 고백으로 바꾸지 않은 약속은 다음 만남의 신뢰가 됐다.</p>:<p>지켜지지 않은 약속과 아직 부족한 신뢰 앞에서 두 사람은 거리를 두었다. 호감만으로는 지킬 수 없는 약속이 있다는 것을, 이번 결말에 남겼다.</p>}<button className="trial-primary" onClick={()=>setEnding(null)}>사건 수첩으로 돌아가기<ArrowRight size={17}/></button></div>}
  {a?.kind==='bond'&&<div className="classroom-story"><SchoolPortrait id={a.id} className="classroom-standing"/><span className="trial-label">FREE TIME / AFFECTION {state.bonds[a.id].affection} / TRUST {state.bonds[a.id].trust}</span>{line?<button className="classroom-dialogue" onClick={()=>next(continueBond(state))}><Speaker line={line} name={name}/><span>CLICK TO CONTINUE <ChevronRight size={17}/></span></button>:<div className="classroom-bond-choices">{bondEpisodes[a.id][a.episode].choices.map((option,index)=><button key={index} onClick={()=>next(selectBondChoice(state,index))}><small>0{index+1}</small>{option.text}<ChevronRight size={16}/></button>)}</div>}</div>}
  {c&&p&&(p.phase==='opening'||p.phase==='closing')&&line&&<div className="classroom-story">{actor?<SchoolPortrait id={actor} className="classroom-standing"/>:line.speaker==='alter'?<div className="classroom-ai-large">ALTER<br/>EGO<small>LOCAL ANALYSIS · READ ONLY</small></div>:null}<span className="trial-label">{p.phase==='opening'?'INCIDENT':'AFTER THE VERDICT'} / CASE 0{c.number}</span><button className="classroom-dialogue" onClick={()=>next(continueCase(state))}><Speaker line={line} name={name}/><span>CLICK TO CONTINUE <ChevronRight size={17}/></span></button></div>}
  {c&&p&&p.phase==='investigation'&&<div className="classroom-investigation"><div className="classroom-section-title"><span className="trial-label">DEADLOCK INVESTIGATION</span><h1>印象より、証拠。<small>인상보다, 증거.</small></h1><p>장소를 돌며 증거 {p.clues.length} / {c.evidence.length} 수집. 파일의 내용과 증언의 확인 범위를 함께 살펴보세요.</p></div><div className="evidence-grid">{c.evidence.map(e=><button className={p.clues.includes(e.id)?'collected':''} key={e.id} onClick={()=>{next(collectEvidence(state,e.id));setInspection(e.id);}}><span><MapPin size={14}/>{locationById[e.location].name}</span><h2>{e.name}</h2><p>{p.clues.includes(e.id)?e.description:'현장을 조사하고 관련자의 증언을 듣는다.'}</p><small>{p.clues.includes(e.id)?<Check size={15}/>:<Search size={15}/>} {p.clues.includes(e.id)?'확보한 자료 다시 확인':'증거 조사'}</small></button>)}</div><button className="trial-primary" disabled={p.clues.length!==c.evidence.length} onClick={()=>next(beginTrial(state))}><Target size={18}/>학급재판 개정 · 모든 증거 필요</button></div>}
  {c&&p&&p.phase==='debate'&&debate&&<div className="classroom-trial"><div className="trial-status"><span className="trial-label">NONSTOP DEBATE / {p.round+1} OF {c.debates.length}</span><div aria-label={`논증 신뢰 ${p.health} / 5`}>{Array.from({length:5},(_,index)=><Shield key={index} size={19} className={index<p.health?'lit':''}/>)}</div></div><h1>{debate.title}</h1><p className="trial-instruction">모순된 문장을 고른 다음, 그 문장을 직접 반박하는 증거를 선택해 논파하세요.</p><div className="debate-speakers">{debate.claims.map((statement,index)=><button key={index} className={claim===index?'targeted':''} disabled={!!p.feedback} onClick={()=>setClaim(index)}>{statement.speaker!=='alter'?<SchoolPortrait id={statement.speaker}/>:<div className="alter-avatar">AE</div>}<span><small>{statement.speaker==='alter'?'ALTER EGO':schoolById[statement.speaker].name}</small>{statement.text}</span><Target size={16}/></button>)}</div><div className="truth-bullets"><span className="trial-label">EVIDENCE / 言弾</span><div>{c.evidence.map(e=><button className={bullet===e.id?'selected':''} key={e.id} disabled={!!p.feedback} onClick={()=>setBullet(e.id)}><Zap size={13}/>{e.name}</button>)}</div>{bullet&&<p>{c.evidence.find(e=>e.id===bullet)?.description}</p>}</div>{p.feedback?<div className={`rebuttal-result ${p.feedback.ok?'correct':'incorrect'}`} role="status"><strong>{p.feedback.ok?'論破!':'根拠不足'}</strong><p>{p.feedback.text}</p><button className="trial-primary" onClick={()=>next(continueCase(state))}>{p.feedback.ok?'논증 이어가기':'다시 검토하기'}<ArrowRight size={17}/></button></div>:<div className="trial-actions"><button className="trial-primary" disabled={claim===null||bullet===null} onClick={()=>next(rebut(state,claim!,bullet!))}><Target size={18}/>이 증거로 논파한다</button><button className="trial-hint" disabled={!canHint} onClick={()=>setHint(!hint)}>{canHint?'주한과 반장에게 논점 확인':'두 새 인물의 신뢰 20부터 논점 힌트'}</button>{hint&&<p className="hint-text">{debate.hint}</p>}</div>}</div>}
  {c&&p&&p.phase==='reconstruction'&&<div className="classroom-reconstruct"><span className="trial-label">CLOSING ARGUMENT / 신뢰 {p.health}</span><h1>흩어진 장면을<br/><em>시간 순서로.</em></h1><div className="sequence-slots">{c.sequence.map((_,index)=><div key={index}><small>0{index+1}</small>{p.order[index]??'장면을 선택하세요'}</div>)}</div><div className="sequence-options">{[...c.sequence].map((_,index)=>c.sequence[(index*3+1)%c.sequence.length]).map(event=><button key={event} disabled={p.order.includes(event)} onClick={()=>next(addSequence(state,event))}>{event}</button>)}</div>{p.feedback&&<p className="trial-warning" role="status">{p.feedback.text}</p>}<div className="trial-actions"><button className="trial-primary" disabled={p.order.length!==c.sequence.length} onClick={()=>next(submitSequence(state))}>사건 재구성 확정<ArrowRight size={17}/></button><button className="trial-hint" onClick={()=>next(clearSequence(state))}>순서 다시 놓기</button></div></div>}
  {c&&p&&p.phase==='verdict'&&<div className="classroom-verdict"><span className="trial-label">CLASS VERDICT / 신뢰 {p.health}</span><h1>{c.id==='absence'?'잘못 전달된 기록에':'이 사건의 행위에'}<br/><em>책임이 있는 사람은?</em></h1><p>인물의 성격이 아니라 재판에서 확인한 행동을 근거로 고르세요.</p><div className="verdict-cast">{schoolCharacters.map(person=><button key={person.id} onClick={()=>next(vote(state,person.id))}><SchoolPortrait id={person.id}/><span>{person.name}</span></button>)}</div>{p.feedback&&<p className="trial-warning" role="status">{p.feedback.text}</p>}</div>}
  {c&&p&&p.phase==='motive'&&<div className="classroom-motive"><span className="trial-label">THE REASON BEHIND THE ACT / 신뢰 {p.health}</span><h1>그 행동 뒤에<br/><em>무엇이 있었을까?</em></h1><p>발견된 자료와 당사자의 설명을 모두 만족하는 결론을 고르세요.</p>{c.motives.map((motive,index)=><button key={motive} onClick={()=>next(explainMotive(state,index))}><small>0{index+1}</small>{motive}<ChevronRight size={17}/></button>)}{p.feedback&&<p className="trial-warning" role="status">{p.feedback.text}</p>}</div>}
  {c&&p&&p.phase==='failed'&&<div className="classroom-failure"><span className="trial-label">BAD VERDICT</span><h1>학급의 오판</h1><p>근거가 약한 지목을 반복하자 모두의 말이 끊겼다. 오늘의 결론은 기록할 수 없었다. 확인한 자료를 들고 다시 처음의 논점부터 시작하자.</p><button className="trial-primary" onClick={()=>next(retryTrial(state))}>확보한 증거로 재심 시작<ArrowRight size={17}/></button><button className="trial-hint" onClick={back}>사건 수첩으로</button></div>}
  {c&&p&&p.phase==='solved'&&<div className="classroom-solved"><span className="trial-label">CASE RESOLVED</span><h1>{c.title}</h1><p className="resolved-name">책임 확인 · {schoolById[c.culprit].name}</p><div>{c.closing.map((l,index)=><Speaker key={index} line={l} name={name}/>)}</div><button className="trial-primary" onClick={back}>다음 약속으로 돌아가기<Heart size={17}/></button></div>}
  {inspected&&<div className="evidence-inspection" role="dialog" aria-label={inspected.name}><button className="inspection-close" onClick={()=>setInspection(null)} aria-label="증거 확인 닫기"><X size={19}/></button><span className="trial-label">TRUTH BULLET ACQUIRED</span><h2>{inspected.name}</h2><p>{inspected.description}</p>{inspected.inspection.map((l,index)=><Speaker key={index} line={l} name={name}/>)}<button className="trial-primary" onClick={()=>setInspection(null)}>수첩에 기록<Check size={16}/></button></div>}
 </section>;
}
