import {useEffect,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,ChevronRight,Heart,MapPin,Maximize,Menu,Music2,NotebookPen,Pause,Play,RotateCcw,Save,Search,Settings,ShieldCheck,SkipForward,Volume2,VolumeX,X} from 'lucide-react';
import {schoolById} from './data/classroomMystery';
import {locationById} from './data/characters';
import {SchoolPortrait} from './SchoolPortrait';
import {CampusMap} from './CampusMap';
import RomanceActivity from './RomanceActivity';
import {EvidenceViewer} from './EvidenceViewer';
import {TrialRevolver,RebuttalBurst} from './TrialRevolver';
import {hasHangoutAvailable,getHangoutScene} from './data/romanceHangouts';
import {romanceArt,artById,artPath,awareness} from './data/romanceArt';
import {getRomanceActivity} from './data/romanceActivities';
import {music} from './engine/audio';
import {shuffleChoices} from './engine/choiceOrder';
import {newRomance,currentRomanceScene,romanceLines,advanceRomance,chooseRomance,nextRomance,selectFocus,startHangout,completeRomanceActivity,respondToActivity,conveneTrial,availableMemories,inspectMemory,submitArgument,continueArgument,submitReconstruction,setVerdict,personLocation,choiceOrder,junyeonCap} from './engine/romance';
import {saveRomance,loadRomance,listRomanceSaves,type RomanceSlot} from './engine/romanceStorage';
import {memoryEvidence,romanceTrialRounds,romanceSequence} from './data/romanceMystery';
import {romancePeople,type RPerson,type RState} from './romanceTypes';
import type {LocationId} from './types';
import type {EvidenceVisual} from './data/evidenceVisuals';

type Panel='none'|'notebook'|'bonds'|'save'|'load'|'settings'|'backlog'|'menu'|'gallery';
const chapterTitles=['삼십 분 늦게 온 봄','같이 틀린 박자','서로 다른 곳에서','내일이 오기 전에','빈자리에 남긴 약속'];
const chapterDays=[64,49,31,14,0];
const getStored=<T,>(key:string,fallback:T):T=>{try{const v=localStorage.getItem(`reaction-romance-v2:${key}`);return v?JSON.parse(v):fallback;}catch{return fallback;}};
const persist=(key:string,value:unknown)=>{try{localStorage.setItem(`reaction-romance-v2:${key}`,JSON.stringify(value));}catch{/* Saves report their own failures. */}};
const visualFor=(id:string):EvidenceVisual|undefined=>{const c=memoryEvidence.find(c=>c.id===id);return c?{id:c.id,image:c.image,alt:`${c.name}. ${c.description}`,caption:'게임 속 가상 자료 · 실제 학교나 학생의 기록이 아닙니다.'}:undefined;};
const asSlot=(slot:string):RomanceSlot=>slot==='auto'?'auto':Number(slot) as RomanceSlot;
const bg=(place:LocationId)=>`${import.meta.env.BASE_URL}assets/${locationById[place].bg}.webp`;
const label=(speaker:string)=>speaker==='player'?'나':speaker==='narrator'?'':speaker==='teacher'?'담임 선생님':speaker==='alter'?'얼터에고':schoolById[speaker as RPerson]?.name??'';
const names=(id:RPerson)=>schoolById[id].name;
const together=(id:RPerson)=>`${names(id)}${id==='world'||id==='taewoo'?'와':'과'}`;

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const box=useRef<HTMLElement>(null);
 useEffect(()=>{const old=document.activeElement as HTMLElement|null;box.current?.focus();return()=>old?.focus();},[]);
 return <div className="romance-modal-backdrop" onClick={onClose}><section className="romance-modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={box} onClick={e=>e.stopPropagation()} onKeyDown={e=>{
  if(e.key!=='Tab')return;const elements=Array.from(box.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,[tabindex="0"]')??[]);const first=elements[0],last=elements.at(-1);if(!first)return;
  if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
 }}><header><h2>{title}</h2><button aria-label="창 닫기" onClick={onClose}><X size={21}/></button></header><div className="romance-modal-body">{children}</div></section></div>;
}

export default function RomanceGame(){
 const [game,setGame]=useState<RState|null>(null),[name,setName]=useState(''),[nameError,setNameError]=useState('');
 const [panel,setPanel]=useState<Panel>('none'),[place,setPlace]=useState<LocationId>('classroom');
 const [auto,setAuto]=useState(false),[visible,setVisible]=useState(0),[hidden,setHidden]=useState(document.hidden);
 const [read,setRead]=useState<string[]>(()=>{const v=getStored<unknown>('read',[]);return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];});
 const [collected,setCollected]=useState<string[]>(()=>{const v=getStored<unknown>('endings',[]);return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];});
 const [seenArt,setSeenArt]=useState<string[]>(()=>{const v=getStored<unknown>('art',[]);return Array.isArray(v)?v.filter(x=>typeof x==='string'&&artById(x)):[];});
 const [galleryArt,setGalleryArt]=useState<string|null>(null);
 const [settings,setSettings]=useState(()=>{const v=getStored<Record<string,unknown>>('settings',{});return {speed:[0,12,24,45].includes(Number(v?.speed))?Number(v.speed):24,music:v?.music===true,volume:typeof v?.volume==='number'?Math.max(0,Math.min(.8,v.volume)):.35};});
 const [toast,setToast]=useState(''),[notebookId,setNotebookId]=useState<string|null>(null),[inspectId,setInspectId]=useState<string|null>(null);
 const [selectedClaim,setSelectedClaim]=useState<string|null>(null),[loaded,setLoaded]=useState<string|null>(null),[burst,setBurst]=useState(0),[session,setSession]=useState(0);
 const [overwrite,setOverwrite]=useState<string|null>(null),[titlePerson,setTitlePerson]=useState<RPerson>('world');
 const saveWarned=useRef(false),stateRef=useRef(game);stateRef.current=game;
 const scene=game?currentRomanceScene(game):null,lines=game?romanceLines(game):[];
 const raw=game?lines[game.line]:undefined,text=raw?.text.replaceAll('{name}',game?.name??'')??'';
 const lineKey=game?`${game.sceneKey}:${game.response?'r':'l'}:${game.line}:${raw?.speaker??''}:${text}`:'';
 const order=game?.trialOrder??[];
 const setOrder=(value:string[]|((current:string[])=>string[]))=>setGame(s=>s?{...s,trialOrder:typeof value==='function'?value(s.trialOrder):value}:s);
 const choosing=!!game&&game.phase==='story'&&!game.response&&game.line>=lines.length&&!!scene?.choices.length;
 const choices=game&&scene?choiceOrder(game,scene.choices):[];
 const portrait=raw&&romancePeople.includes(raw.speaker as RPerson)?raw.speaker as RPerson:game?.visitor??lines.slice(0,(game?.line??0)+1).reverse().find(l=>romancePeople.includes(l.speaker as RPerson))?.speaker as RPerson|undefined;
 const memories=game?availableMemories(game):[],localMemories=memories.filter(c=>c.location===place);
 const students=game?romancePeople.filter(id=>!(id==='junyeon'&&game.verdict==='exclude')).map(id=>({id,name:names(id),color:schoolById[id].color,place:personLocation(game,id),available:game.actions>0&&!game.visited.includes(id)&&hasHangoutAvailable(id,game),visited:game.visited.includes(id),exhausted:!hasHangoutAvailable(id,game)})):[];
 const onSite=students.filter(s=>s.place===place);
 const notebook=memoryEvidence.filter(c=>game?.clues.includes(c.id));
 const endingFlag=game?[...game.flags].reverse().find(f=>/^(romance|friendship):/.test(f))?.split(':')[1]:null;
 const endingPerson=romancePeople.includes(endingFlag as RPerson)?endingFlag as RPerson:game?.focus;
 const note=notebook.find(c=>c.id===notebookId)??notebook[0];
 const activeRound=game?romanceTrialRounds[game.trialRound]:undefined;
 const claimOrder=game&&activeRound?shuffleChoices(activeRound.claims,`${game.seed}:${activeRound.id}:claims`).map(x=>x.value):[];
 const sequenceOrder=game?shuffleChoices(romanceSequence,`${game.seed}:reconstruction`).map(x=>x.value):[];
 const trialEvidence=notebook.map(c=>({id:c.id,name:c.name,location:c.location,description:c.description,inspection:[]}));
 const visuals=Object.fromEntries(memoryEvidence.map(c=>[c.id,visualFor(c.id)!]));
 const visualLine=raw??(choosing?scene?.lines.at(-1):undefined);
 const currentArt=artById(visualLine?.art),thought=game?awareness(game):null;
 const encounter:1|2=game?.sceneKey.includes('-v2:')?2:1;
 const invitation=game?.visitor?getRomanceActivity(game.visitor,game.chapter,encounter,game.seed):null;
 const fmt=(s:string)=>s.replaceAll('{name}',game?.name??'');
 const closePanel=()=>{setPanel('none');setOverwrite(null);};
 const tell=(s:string)=>setToast(s);
 const mutate=(f:(s:RState)=>RState)=>setGame(s=>s?f(s):s);
 function step(){if(!game||panel!=='none'||inspectId||game.phase!=='story'||choosing)return;if(visible<text.length){setVisible(text.length);return;}if(text&&!read.includes(lineKey))setRead(r=>[...r,lineKey]);mutate(advanceRomance);}
 function start(e:FormEvent){e.preventDefault();try{const next=newRomance(name,crypto.getRandomValues(new Uint32Array(1))[0]);setGame(next);setNameError('');setAuto(false);setPlace('classroom');}catch{setNameError('이름을 1~12자로 입력해 주세요. 한글·영문·숫자를 사용할 수 있어요.');}}
 function open(p:Panel){setAuto(false);setPanel(p);setOverwrite(null);}
 function load(slot:string){const saved=loadRomance(asSlot(slot));if(!saved){tell('불러올 수 있는 새 버전 저장이 없어요.');return;}setGame(saved.state);setSession(v=>v+1);setPlace(saved.state.location);setAuto(false);closePanel();tell('저장한 약속부터 이어 갑니다.');}
 function save(slot:string){if(!game)return;if(loadRomance(asSlot(slot))&&overwrite!==slot){setOverwrite(slot);return;}if(saveRomance(asSlot(slot),game)){closePanel();tell(`${slot}번 슬롯에 저장했어요.`);}else tell('브라우저 저장 공간을 확인해 주세요.');}
 function next(){if(!game)return;const value=nextRomance(game);if(value===game){const left=memoryEvidence.filter(c=>c.chapter===game.chapter&&!game.clues.includes(c.id));tell(left.length?'이번 장에서 함께 겪은 일을 지도에서 확인해 주세요.':'지금 이야기를 먼저 마쳐 주세요.');return;}setGame(value);setPlace('classroom');}
 function argue(){if(!game||!selectedClaim||!loaded)return;const next=submitArgument(game,selectedClaim,loaded);setGame(next);if(next!==game&&next.trialFeedback?.ok)setBurst(n=>n+1);}
 function fullscreen(){if(document.fullscreenElement)void document.exitFullscreen().catch(()=>tell('전체화면을 종료하지 못했어요.'));else void document.documentElement.requestFullscreen?.().catch(()=>tell('이 브라우저에서는 전체화면을 지원하지 않아요.'));}
 useEffect(()=>{if(!game)return;if(!saveRomance('auto',game)&&!saveWarned.current){saveWarned.current=true;tell('자동 저장을 하지 못했어요. 저장 공간을 확인해 주세요.');}},[game]);
 useEffect(()=>{persist('read',read);},[read]);
 useEffect(()=>{if(game?.phase==='story'&&currentArt)setSeenArt(found=>found.includes(currentArt.id)?found:[...found,currentArt.id]);},[game?.phase,currentArt?.id]);
 useEffect(()=>{persist('art',seenArt);},[seenArt]);
 useEffect(()=>{persist('settings',settings);music(settings.music,settings.volume);return()=>music(false,0);},[settings]);
 useEffect(()=>{const fn=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',fn);return()=>document.removeEventListener('visibilitychange',fn);},[]);
 useEffect(()=>{setVisible(settings.speed===0?text.length:0);},[lineKey,text,settings.speed]);
 useEffect(()=>{if(hidden||panel!=='none'||!text||settings.speed===0||visible>=text.length)return;const t=setTimeout(()=>setVisible(n=>Math.min(n+1,text.length)),settings.speed);return()=>clearTimeout(t);},[visible,text,settings.speed,hidden,panel]);
 useEffect(()=>{if(!auto||hidden||panel!=='none'||inspectId||game?.phase!=='story'||choosing||visible<text.length)return;const t=setTimeout(step,Math.max(1300,text.length*30));return()=>clearTimeout(t);},[auto,hidden,panel,inspectId,lineKey,visible,choosing,game?.phase]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4300);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{setSelectedClaim(null);setLoaded(null);},[game?.trialRound,game?.phase,session]);
 useEffect(()=>{if(game?.phase==='map')setPlace(game.location);},[game?.phase,game?.sceneKey]);
 useEffect(()=>{if(game?.trialFeedback)document.querySelector('.romance-trial-feedback')?.scrollIntoView({block:'nearest'});},[game?.trialFeedback]);
 useEffect(()=>{if(game?.phase==='ending'&&game.ending&&!collected.includes(game.ending)){const all=[...collected,game.ending];setCollected(all);persist('endings',all);}},[game?.phase,game?.ending]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();if(inspectId)setInspectId(null);else if(panel!=='none')closePanel();else open('menu');return;}if(panel!=='none'||inspectId||e.ctrlKey||e.metaKey||e.altKey||(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,button,a')))return;if(game?.phase==='story'&&(e.key===' '||e.key==='Enter')){e.preventDefault();step();}else if(choosing&&/^[1-9]$/.test(e.key)){const c=choices[Number(e.key)-1];if(c){e.preventDefault();mutate(s=>chooseRomance(s,c.value.id));}}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);});

 return <main className={`romance-app${game?' in-game':''}`}>
  <div className="romance-backdrop" style={{backgroundImage:`url(${bg(game?(game.phase==='map'?place:visualLine?.location??scene?.location??game.location):'classroom')})`}}/>
  <header className="romance-header"><button className="romance-brand" onClick={()=>open('menu')} aria-label="메뉴 열기"><span>RE:ACTION</span><small>빈자리에 남긴 약속</small></button><div className="romance-header-right">{game&&<span className="romance-calendar">{game.date}<small>{game.chapter+1}장 · 1학년 1반</small></span>}<button aria-label={settings.music?'배경음 끄기':'배경음 켜기'} onClick={()=>setSettings(s=>({...s,music:!s.music}))}>{settings.music?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button aria-label="전체화면" onClick={fullscreen}><Maximize size={19}/></button><button aria-label="설정" onClick={()=>open('settings')}><Settings size={19}/></button><button aria-label="메뉴" onClick={()=>open('menu')}><Menu size={21}/></button></div></header>

  {!game?<section className="romance-title"><div className="romance-title-copy"><span className="romance-kicker">LOVE FIRST. THE TRUTH COMES LATER.</span><h1>너와의 약속을,<br/><em>기억할게.</em></h1><p>같은 반, 다른 마음. 페어까지 남은 64일.<br/>함께한 시간이 쌓이면 비어 있던 자리의 이유도 알게 됩니다.</p><form onSubmit={start}><label htmlFor="romance-name">새로 온 전학생, 이름이 뭐야?</label><div className="romance-name-box"><input id="romance-name" value={name} onChange={e=>{setName(e.target.value);setNameError('');}} maxLength={12} autoComplete="off" placeholder="이름을 입력해 주세요" aria-describedby="romance-name-help" aria-invalid={!!nameError}/><NotebookPen size={20}/></div><small id="romance-name-help" className={nameError?'romance-error':''}>{nameError||'기본 이름 없이, 당신의 이름으로 시작합니다.'}</small><button className="r-primary" disabled={!name.trim()} type="submit">새로운 이야기 시작<ArrowRight size={18}/></button></form><div className="romance-title-links"><button onClick={()=>open('load')}><BookOpen size={16}/>이어서 하기</button><button onClick={()=>open('gallery')}><Heart size={16}/>기억의 서랍</button></div><div className="romance-edition"><b>5 CHAPTERS / ONE FINAL TRIAL</b><span>1~4장 일상과 연애 · 5장 모아 둔 기록으로 학급재판</span><small>새 이야기의 저장은 이전 버전과 분리됩니다. 기존 저장은 삭제하지 않습니다.</small></div></div><aside className="romance-cast-preview"><div className="romance-featured-person"><SchoolPortrait id={titlePerson}/><div><small>{schoolById[titlePerson].role}</small><h2>{names(titlePerson)}</h2><p>“{schoolById[titlePerson].quote}”</p></div></div><div className="romance-cast-tabs" aria-label="등장인물 둘러보기">{romancePeople.map(id=><button key={id} aria-pressed={titlePerson===id} onClick={()=>setTitlePerson(id)}><SchoolPortrait id={id}/><span>{names(id)}</span></button>)}</div></aside><footer>등장인물·학교 생활·사건·시설은 허구입니다. / STORY EDITION 3.0</footer></section>:<>

   {game.phase==='story'&&scene&&<section className="romance-story" aria-label="이야기" inert={panel!=='none'||!!inspectId}><div className={`romance-stage${currentArt?' has-event-art':''}`}><div className="romance-scene-title"><span>{game.mode==='discovery'?'A NOTE FROM TODAY':game.mode==='hangout'?'AFTER SCHOOL':game.mode==='repair'?'FOUR WEEKS TO REBUILD':'OUR SHARED DAYS'}</span><h1>{scene.title}</h1><p><MapPin size={14}/>{locationById[visualLine?.location??scene.location].name}</p></div>{currentArt?<figure className="romance-event-art" key={currentArt.id}><img src={`${import.meta.env.BASE_URL}${artPath(currentArt.id)}`} alt={currentArt.alt}/><figcaption><Heart size={13}/>{currentArt.title}<button onClick={()=>{setGalleryArt(currentArt.id);open('gallery');}}>그림 보기</button></figcaption></figure>:scene.image?<img className="romance-scene-art" src={`${import.meta.env.BASE_URL}${scene.image}`} alt={`${scene.title} - 함께한 순간`}/>:portrait&&<div className={`romance-portrait-card emotion-${visualLine?.expression??'neutral'}`} key={portrait}><SchoolPortrait id={portrait}/><span>{schoolById[portrait].role}</span></div>}</div><div className={`romance-dialogue${choosing?' with-choices':''}`}>
    {choosing?<><div className="romance-choice-heading"><Heart size={18}/>어떤 말을 건넬까?</div><div className="romance-choices">{choices.map(({value},i)=><button key={value.id} onClick={()=>mutate(s=>chooseRomance(s,value.id))}><span>{String(i+1).padStart(2,'0')}</span><b>{fmt(value.text)}</b><ChevronRight size={18}/></button>)}</div></>:<button className="romance-line" onClick={step} aria-label={text?`${raw?.speaker==='player'?game.name:label(raw?.speaker??'')} ${text} - 다음 대사`:'이야기 이어가기'}><b>{raw?.speaker==='player'?game.name:label(raw?.speaker??'')}</b><p>{text.slice(0,visible)||(!text?'이야기 이어가기':' ')}</p><span>{visible<text.length?'클릭하면 문장 전체 표시':game.mode==='discovery'&&game.line===lines.length-1?'계속하면 기억 수첩에 기록합니다':'CLICK / SPACE TO CONTINUE'}<ChevronRight size={18}/></span></button>}
   </div><nav className="romance-toolbar" aria-label="대화 도구"><button onClick={()=>open('backlog')}><BookOpen size={15}/>기록</button><button aria-pressed={auto} onClick={()=>setAuto(!auto)}>{auto?<Pause size={15}/>:<Play size={15}/>}자동</button><button disabled={!read.includes(lineKey)||choosing} onClick={()=>{setVisible(text.length);mutate(advanceRomance);}}><SkipForward size={15}/>읽은 대사</button><button onClick={()=>open('notebook')}><NotebookPen size={15}/>기억</button><button onClick={()=>open('bonds')}><Heart size={15}/>관계</button><button onClick={()=>open('save')}><Save size={15}/>저장</button></nav></section>}

   {game.phase==='map'&&<section className="romance-map" inert={panel!=='none'||!!inspectId}><div className="romance-map-heading"><div><span className="romance-kicker">AFTER SCHOOL / {game.act+1} OF 3</span><h1>오늘은, 누구와 함께할까?</h1></div><div className="romance-actions"><b>{game.actions}</b><span>남은 만남<small>기록 확인은 소모 없음</small></span></div></div><div className="romance-map-body"><CampusMap selected={place} students={students} locked={()=>false} onSelect={setPlace} discoveries={Object.fromEntries(memories.map(c=>[c.location,memories.filter(x=>x.location===c.location).length]))}/><aside className="romance-place"><img className="romance-place-background" src={bg(place)} alt={locationById[place].name}/><div className="romance-place-content"><small>{locationById[place].sub}</small><h2>{locationById[place].name}</h2>{localMemories.map(c=><button key={c.id} className="romance-memory-discovery" onClick={()=>{setAuto(false);mutate(s=>inspectMemory({...s,location:place},c.id));}}><Search size={18}/><span><b>{c.spot}</b><small>{c.lead}</small><i>함께 확인하기 · 행동 소모 없음</i></span><ChevronRight size={18}/></button>)}{onSite.length?onSite.map(p=><div className="romance-meeting" key={p.id}><SchoolPortrait id={p.id}/><div><b>{p.name}{game.focus===p.id&&<Heart size={12}/>}</b><small>{p.exhausted?'이번 장의 두 약속을 함께했어요':getHangoutScene(p.id,game,p.place).title}</small><div><button disabled={!p.available} onClick={()=>{setAuto(false);mutate(s=>startHangout(s,p.id,place));}}>{getHangoutScene(p.id,game,p.place).location===place?'만나러 가기':`함께 ${locationById[getHangoutScene(p.id,game,p.place).location].name} 가기`}</button></div>{!p.available&&<small>{p.exhausted?'다음 장에서 새로운 이야기가 이어져요.':p.visited?'이 시간에는 이미 만났어요.':'남은 만남이 없어요.'}</small>}</div></div>):<p className="romance-quiet">지금은 조용한 곳이에요.<br/>다른 장소에서 친구를 찾아볼까요?</p>}</div></aside></div><footer className="romance-map-footer"><button onClick={()=>open('notebook')}><NotebookPen size={16}/>마음의 기록 <b>{game.clues.length}/8</b></button><p className="romance-awareness"><b>{thought?.title}</b><span>{thought?.text}</span></p><button className="r-primary" onClick={next}>{game.act<2?'다음 이야기':game.chapter===4?'약속의 다음 페이지':game.chapter===1?'가장 만나고 싶은 사람':'다음 장으로'}<ArrowRight size={17}/></button></footer></section>}

   {game.phase==='focus'&&<section className="romance-focus" inert={panel!=='none'}><header><span className="romance-kicker">THE PERSON ON YOUR CALENDAR</span><h1>앞으로 더 만나고 싶은 사람.</h1><p>누구의 다음 이야기가 궁금한가요? 선택한 사람과 3~5장의 약속이 이어집니다.</p></header><div className="romance-focus-grid">{romancePeople.map(id=><button key={id} onClick={()=>mutate(s=>selectFocus(s,id))}><SchoolPortrait id={id}/><span><b>{names(id)}</b><small>{id==='junyeon'?'아직은 친구로, 조금 더 곁에':'둘만의 약속을 이어가기'}</small><i>{schoolById[id].tag}</i></span><ChevronRight size={18}/></button>)}</div><button className="r-secondary" onClick={()=>mutate(s=>selectFocus(s,null))}>아직 한 사람으로 정하지 않고, 친구들과 지낸다</button></section>}

   {game.phase==='activity-invite'&&game.visitor&&<section className="romance-invitation" inert={panel!=='none'}><SchoolPortrait id={game.visitor}/><div><span className="romance-kicker">A LITTLE MORE TIME TOGETHER</span><h1>{invitation?.title}</h1><p>{invitation?.invitation}</p><div className="romance-inline"><button className="r-primary" onClick={()=>mutate(s=>respondToActivity(s,true))}>함께 해 보기<ArrowRight size={17}/></button><button className="r-secondary" onClick={()=>mutate(s=>respondToActivity(s,false))}>오늘의 만남 마치기</button></div><small>활동을 하지 않아도 방금의 대화와 선택은 그대로 남아요.</small></div></section>}
   {game.phase==='activity'&&game.visitor&&<RomanceActivity key={`${session}:${game.sceneKey}`} person={game.visitor} chapter={game.chapter} encounter={encounter} seed={game.seed} paused={panel!=='none'||!!inspectId} onFinish={score=>mutate(s=>completeRomanceActivity(s,score))}/>}
   {game.phase==='trial-briefing'&&<section className="romance-trial-briefing" inert={panel!=='none'}><span className="romance-kicker">09:10 / 1학년 1반</span><h1>누군가를 몰아세우기 위해서가 아니라,<br/>오늘의 무대를 지키기 위해.</h1><p>공연 취소 요청에 적힌 내용이 사실인지, 담임 선생님 입회 아래 확인하기로 했다.<br/>각자 따로 겪은 일을 한자리에 놓아야, 잘못 전달된 이야기를 바로잡을 수 있다.</p><ol><li><b>세계 · 태우</b><span>쪽지와 예약이 실제로 어떻게 달랐는지 설명한다.</span></li><li><b>주한 · 서율 · 현솔</b><span>공개된 안내와 버전 기록을 비교한다. 타인의 사적인 기록은 열지 않는다.</span></li><li><b>태훈 · 민혁 · 나</b><span>날짜 순서를 맞추고, 확인한 사실과 아직 모르는 것을 구분한다.</span></li></ol><p className="romance-trial-rule">준연에게도 설명할 시간이 있다. 결론을 정해 놓고 시작하지 않는다.</p><button className="r-primary" onClick={()=>mutate(conveneTrial)}>모아 둔 기록을 펼친다<NotebookPen size={18}/></button></section>}

   {game.phase==='trial'&&<section className="romance-trial" inert={panel!=='none'||!!inspectId}><header><span className="romance-kicker">CHAPTER 05 / OUR CLASS TRIAL</span><h1>{activeRound?activeRound.title:'우리가 겪은 일을 순서대로'}</h1><p>기억은 근거가 됩니다. 추측만으로 사람의 마음을 단정하지 않습니다.</p></header>{activeRound?<div className="romance-trial-body"><div className="romance-claims"><h2>어느 말에 모순이 있을까?</h2>{claimOrder.map((c,i)=><button key={c.id} disabled={!!game.trialFeedback} aria-pressed={selectedClaim===c.id} onClick={()=>setSelectedClaim(c.id)}><small>{i+1} / {label(c.speaker)}</small><p>{fmt(c.text)}</p></button>)}{game.trialFeedback?<div className={`romance-trial-feedback ${game.trialFeedback.ok?'correct':''}`} role="status"><b>{game.trialFeedback.ok?'확인된 사실':'다시 살펴볼 부분'}</b><p>{game.trialFeedback.text}</p><button className="r-primary" onClick={()=>mutate(continueArgument)}>논증 이어가기<ArrowRight size={16}/></button></div>:<button className="r-primary" disabled={!selectedClaim||!loaded} onClick={argue}>선택한 발언에 증거 제시<ArrowRight size={17}/></button>}</div><TrialRevolver evidence={trialEvidence} selected={loaded} disabled={!!game.trialFeedback} onSelect={setLoaded} onInspect={setInspectId} visuals={visuals}/><div className="romance-mobile-submit">{game.trialFeedback?<button className="r-primary" onClick={()=>mutate(continueArgument)}>논증 이어가기<ArrowRight size={16}/></button>:<button className="r-primary" disabled={!selectedClaim||!loaded} onClick={argue}>선택한 발언에 증거 제시<ArrowRight size={17}/></button>}</div></div>:<div className="romance-reconstruction"><p>1~4장에서 확인한 변화의 순서를 정리해 주세요. 오답으로 관계 점수를 잃지 않습니다.</p><div className="romance-sequence-slots">{Array.from({length:4},(_,i)=><div key={i}><b>{i+1}</b><span>{romanceSequence.find(x=>x.id===order[i])?.text??'아직 놓지 않은 기록'}</span></div>)}</div><div className="romance-sequence-options">{sequenceOrder.map(s=><button key={s.id} disabled={order.includes(s.id)||!!game.trialFeedback} onClick={()=>setOrder(v=>[...v,s.id])}>{s.text}</button>)}</div>{game.trialFeedback?<div role="status" className="romance-trial-feedback"><p>{game.trialFeedback.text}</p><button className="r-primary" onClick={()=>{mutate(continueArgument);setOrder([]);}}>다시 이어가기</button></div>:<div className="romance-inline"><button className="r-secondary" onClick={()=>setOrder([])}>순서 다시 놓기</button><button className="r-primary" disabled={order.length!==4} onClick={()=>mutate(s=>submitReconstruction(s,order))}>이 순서로 확인하기</button></div>}</div>}</section>}

   {game.phase==='verdict'&&<section className="romance-verdict" inert={panel!=='none'}><span className="romance-kicker">SAME TRUTH / DIFFERENT NEXT STEPS</span><h1>이제, 어떤 관계로 남을까?</h1><p>준연은 자신이 바꾼 약속과 공지를 인정했습니다.<br/>외로웠다는 말은 들었지만, 훼방 놓은 책임이 없어지지는 않습니다.</p><div><button onClick={()=>mutate(s=>setVerdict(s,'exclude'))}><span>01 / 관계 단절</span><h2>프로젝트에서는 여기까지 하자.</h2><p>공동 준비에서 내보내고 개인적인 약속을 끝냅니다. 준연의 수습은 교사와 별도로 계속됩니다. 학교 퇴학이나 따돌림을 뜻하지 않습니다.</p><small>준연 동행 종료 · 기존 연애 루트 유지</small><ArrowRight size={19}/></button><button onClick={()=>mutate(s=>setVerdict(s,'forgive'))}><span>02 / 용서와 두 번째 기회</span><h2>바꾼 것부터 바로잡아 줘.</h2><p>제한된 역할로 책임을 다할 기회를 줍니다. 그 뒤 네 주 동안 신뢰를 새로 쌓습니다. 다른 친구들의 용서까지 대신 결정하지는 않습니다.</p><small>호감 상한 70 → 100 · 현재 수치는 그대로 · 연애는 별도 선택</small><ArrowRight size={19}/></button></div><small>어느 선택도 다른 히로인들의 호감을 일괄 변경하지 않습니다.</small></section>}

   {game.phase==='ending'&&<section className="romance-ending" inert={panel!=='none'}><span className="romance-kicker">A PROMISE WE KEPT / MEMORY SAVED</span>{endingPerson&&<SchoolPortrait id={endingPerson}/>}<h1>{game.flags.some(f=>f.startsWith('romance:'))?'다음 약속도, 너와.':endingPerson==='junyeon'&&game.verdict==='exclude'?'비워 둔 자리를 접으며':'우리의 속도로, 다음 페이지.'}</h1><p>{endingPerson?`${together(endingPerson)} 함께 보낸 다섯 장의 기록.`:'한 사람으로 정하지 않아도, 함께 보낸 날들은 남습니다.'}</p><div className="romance-ending-notes"><p>{game.verdict==='forgive'?'준연에게는 책임을 다하는 두 번째 기회를 주었습니다. 용서와 연애는 서로 다른 선택으로 남았습니다.':'준연과의 개인적인 약속을 끝냈습니다. 그 선택은 다른 사람과 지킨 약속을 지우지 않았습니다.'}</p><p>{game.flags.some(f=>f.startsWith('romance:'))?'고백은 누군가를 논파한 보상이 아니라, 서로의 시간을 기억하고 다시 만나기로 한 대답이었습니다.':'마지막 말 한마디보다 함께 보낸 시간이 관계를 정했습니다. 오늘의 마음을 서두르지 않기로 했습니다.'}</p></div><div className="romance-inline"><button className="r-secondary" onClick={()=>open('backlog')}>마지막 대사 다시 읽기</button><button className="r-primary" onClick={()=>{setGame(null);setAuto(false);setName('');}}>새로운 이야기<RotateCcw size={16}/></button></div></section>}
  </>}

  {panel!=='none'&&<Modal title={{notebook:'마음의 기록',bonds:'우리 사이',save:'약속 저장하기',load:'이어 읽을 페이지',settings:'읽기와 소리',backlog:'함께 나눈 말',menu:'잠시 책갈피를 끼워 둘까?',gallery:'기억의 서랍'}[panel]} onClose={closePanel}>
   {panel==='notebook'&&thought&&<div className="romance-notice"><b>{thought.title}</b><p>{thought.text}</p></div>}
   {panel==='notebook'&&(notebook.length?<div className="romance-notebook"><nav aria-label="찾아 둔 기록">{notebook.map(c=><button key={c.id} aria-pressed={note?.id===c.id} onClick={()=>setNotebookId(c.id)}><span>{c.code} / {c.chapter+1}장</span><b>{c.name}</b><small>{locationById[c.location].name}</small></button>)}</nav>{note&&<article><h3>{note.name}</h3><EvidenceViewer evidenceId={note.id} visual={visualFor(note.id)}/><p>{note.description}</p><div className="romance-note-limit"><b>이 기록만으로 알 수 없는 것</b><p>{note.limit}</p></div></article>}</div>:<div className="romance-empty"><NotebookPen size={36}/><h3>아직 적어 둔 기록이 없어요.</h3><p>1~4장의 자유 행동에서 직접 겪은 어긋남을 확인하면, 그때의 자료가 이곳에 남습니다. 재판은 5장에만 열립니다.</p></div>)}
   {panel==='bonds'&&game&&<div className="romance-bonds">{romancePeople.map(id=><article key={id}><SchoolPortrait id={id}/><div><h3>{names(id)} {game.focus===id&&<Heart size={15}/>}</h3><small>{id==='junyeon'?(game.verdict==='exclude'?'개인 동행 종료':game.verdict==='forgive'?'다시 쌓는 관계':'가까워져도, 아직 망설이는 친구'):schoolById[id].tag}</small><label>호감 <b>{game.bonds[id].affection}{id==='junyeon'?` / ${junyeonCap(game)}`:' / 100'}</b></label><meter min={0} max={100} value={game.bonds[id].affection}/><label>신뢰 <b>{game.bonds[id].trust} / 100</b></label><meter min={0} max={100} value={game.bonds[id].trust}/></div></article>)}</div>}
   {(panel==='save'||panel==='load')&&<><p className="romance-panel-intro">자동 저장 1개 · 수동 저장 10개. 새 이야기 저장만 표시하며, 구버전 기록은 브라우저에 그대로 보존합니다.</p><div className="romance-save-grid">{['auto',...Array.from({length:10},(_,i)=>String(i+1))].map(slot=>{const saved=loadRomance(asSlot(slot));return <button key={slot} disabled={panel==='save'?slot==='auto'||!game:!saved} onClick={()=>panel==='save'?save(slot):load(slot)}><small>{slot==='auto'?'AUTO SAVE':`SLOT ${slot.padStart(2,'0')}`}</small><b>{saved?`${saved.state.name} · ${saved.state.chapter+1}장`:'아직 쓰이지 않은 페이지'}</b><span>{saved?new Date(saved.savedAt).toLocaleString('ko-KR'):'새로운 약속을 남길 자리'}</span>{overwrite===slot&&<em>한 번 더 누르면 기존 저장을 덮어씁니다.</em>}</button>;})}</div></>}
   {panel==='settings'&&<div className="romance-settings"><label>대사 표시 속도<select value={settings.speed} onChange={e=>setSettings(s=>({...s,speed:Number(e.target.value)}))}><option value={45}>천천히</option><option value={24}>보통</option><option value={12}>빠르게</option><option value={0}>즉시 표시</option></select></label><label>배경음<input type="checkbox" checked={settings.music} onChange={e=>setSettings(s=>({...s,music:e.target.checked}))}/></label><label>음량<input type="range" min="0" max="0.8" step="0.05" value={settings.volume} onChange={e=>setSettings(s=>({...s,volume:Number(e.target.value)}))}/></label><p>Space / Enter: 대사 넘기기 · 숫자키: 화면 순서의 선택지 · Esc: 메뉴.<br/>운영체제의 동작 줄이기 설정을 적용합니다. 자동 진행은 선택지에서 멈춥니다.</p></div>}
   {panel==='backlog'&&<div className="romance-log">{game?.backlog.length?game.backlog.map((l,i)=><p key={i}><b>{l.speaker==='player'?game.name:label(l.speaker)}</b>{fmt(l.text)}</p>):<p>아직 나눈 대사가 없어요.</p>}</div>}
   {panel==='gallery'&&<div className="romance-art-gallery"><h3>함께한 순간 · {seenArt.length} / {romanceArt.length}</h3>{galleryArt&&seenArt.includes(galleryArt)&&<figure><img src={`${import.meta.env.BASE_URL}${artPath(galleryArt)}`} alt={artById(galleryArt)?.alt}/><figcaption>{artById(galleryArt)?.title}<a className="r-secondary" href={`${import.meta.env.BASE_URL}${artPath(galleryArt)}`} download={`RE_ACTION-${galleryArt}.png`}>원본 저장</a></figcaption></figure>}<div className="romance-art-grid">{romanceArt.map(art=><button key={art.id} disabled={!seenArt.includes(art.id)} onClick={()=>setGalleryArt(art.id)}>{seenArt.includes(art.id)?<img src={`${import.meta.env.BASE_URL}${artPath(art.id)}`} alt={art.alt} loading="lazy"/>:<span className="romance-art-lock"><Heart size={24}/></span>}<b>{names(art.person)}</b><small>{seenArt.includes(art.id)?art.title:'아직 만나지 않은 순간'}</small></button>)}</div></div>}
   {panel==='gallery'&&<div className="romance-gallery"><p>새 이야기에서 만난 결말 {collected.length}개. 이전 버전의 수집 기록도 삭제하지 않고 보존합니다.</p>{collected.length?collected.map(id=><div key={id}><Heart size={18}/><span>{id.split(':').map(part=>romancePeople.includes(part as RPerson)?names(part as RPerson):({romance:'연애',friendship:'우정',friend:'우정',exclude:'관계 단절',forgive:'두 번째 기회',normal:'우리의 다음 페이지',alone:'나의 다음 페이지',class:'1반 친구들'}[part]??part)).join(' · ')}</span></div>):<div className="romance-empty">아직 마지막 페이지에 도착하지 않았어요.</div>}</div>}
   {panel==='menu'&&<div className="romance-menu">{game&&<><button onClick={()=>open('save')}><Save size={18}/>저장하기</button><button onClick={()=>open('notebook')}><NotebookPen size={18}/>마음의 기록</button><button onClick={()=>open('bonds')}><Heart size={18}/>우리 사이</button></>}<button onClick={()=>open('load')}><BookOpen size={18}/>이어서 하기 <small>{listRomanceSaves().length}개 저장</small></button><button onClick={()=>open('settings')}><Settings size={18}/>설정</button><button onClick={()=>open('gallery')}><Heart size={18}/>기억의 서랍</button>{game&&<button onClick={()=>{setGame(null);setAuto(false);closePanel();}}><ArrowLeft size={18}/>제목 화면으로 · 자동 저장 유지</button>}<button className="r-primary" onClick={closePanel}>계속하기<Play size={17}/></button><p>로맨스 스토리 3.0 / 5장 · 마지막 한 번의 학급재판<br/>준연의 두 결말은 다른 일곱 명의 연애와 별도로 이어집니다.</p></div>}
  </Modal>}
  {inspectId&&<Modal title="기록 원본 보기" onClose={()=>setInspectId(null)}><EvidenceViewer evidenceId={inspectId} visual={visualFor(inspectId)}/><p>{memoryEvidence.find(c=>c.id===inspectId)?.limit}</p></Modal>}
  {!!burst&&game?.phase==='trial'&&<RebuttalBurst key={burst} eventId={`romance-${burst}`}/>}
  {toast&&<div className="romance-toast" role="status">{toast}</div>}
 </main>;
}
