// Generated by scripts/build-illustration-moments.mjs from completed art manifests.
// Deliberately contains only playable scene data, never image prompts or local paths.
import type {RLine,RPerson,RScene,RState} from '../romanceTypes';
import type {LocationId} from '../types';

export type IllustrationMoment={id:string;person:RPerson;chapter:number;visit:1|2;title:string;location:LocationId;lines:RLine[];bridge:string};
export const illustrationMoments:readonly IllustrationMoment[] = [
  {
    "id": "world-moment-01",
    "person": "world",
    "chapter": 0,
    "visit": 1,
    "title": "정문에서 돌아본 순간",
    "location": "gate",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정문을 지나던 세계가 내 발소리가 멈춘 걸 알아채고 돌아봤다."
      },
      {
        "speaker": "world",
        "text": "길 외우는 중이야? 그렇게 서 있으면 학교가 먼저 외우겠다."
      },
      {
        "speaker": "player",
        "text": "표지판보다 네가 먼저 눈에 들어와서."
      },
      {
        "speaker": "world",
        "text": "그럼 오늘 길 안내는 내가 해. 내일부터는 네 차례고."
      }
    ],
    "bridge": "세계가 안내한 길 끝에서 밴드실 문이 열렸고, 책상 위 녹음기의 재생등이 먼저 눈에 들어왔다."
  },
  {
    "id": "world-moment-02",
    "person": "world",
    "chapter": 0,
    "visit": 2,
    "title": "녹음 버튼 앞의 숨",
    "location": "media",
    "lines": [
      {
        "speaker": "narrator",
        "text": "녹음 신호가 켜지자 세계의 평소 목소리가 갑자기 단정해졌다."
      },
      {
        "speaker": "world",
        "text": "이상하지. 네 앞에선 잘하는데 마이크 앞에선 자기소개부터 어려워."
      },
      {
        "speaker": "player",
        "text": "마이크도 잠깐 모르는 친구라고 생각해 봐."
      },
      {
        "speaker": "world",
        "text": "그러면 네가 먼저 질문해. 혼자 잘하는 척은 오늘 그만할래."
      }
    ],
    "bridge": "방금 녹음은 지우고 밴드실 마이크로 다시 해 보기로 했지만, 소개말 앞에서 세계의 입술이 또 한번 멈췄다."
  },
  {
    "id": "world-moment-03",
    "person": "world",
    "chapter": 1,
    "visit": 1,
    "title": "플러그 끝의 작은 박자",
    "location": "band",
    "lines": [
      {
        "speaker": "narrator",
        "text": "세계는 케이블을 끼우기 전에 발끝으로 박자를 두 번 쳤다."
      },
      {
        "speaker": "world",
        "text": "처음 소리 날 때 놀라지 마. 볼륨은 낮췄는데 기대는 못 낮췄어."
      },
      {
        "speaker": "player",
        "text": "그럼 내가 놀라는 표정은 감상에 포함하지 마."
      },
      {
        "speaker": "world",
        "text": "포함할 건데. 내 첫 관객 반응은 다 듣고 싶거든."
      }
    ],
    "bridge": "기타 케이블을 연결한 세계가 노래를 시작하려다 눈앞을 가린 마이크대를 올려다봤다."
  },
  {
    "id": "world-moment-04",
    "person": "world",
    "chapter": 1,
    "visit": 2,
    "title": "젓가락 끝의 협상",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "급식 쟁반 한쪽에 남은 만두를 두고 세계가 지휘자처럼 젓가락을 들었다."
      },
      {
        "speaker": "world",
        "text": "마지막 한 개. 지금 양보하면 나중에 서운하다고 노래할 수도 있어."
      },
      {
        "speaker": "player",
        "text": "차라리 가위바위보로 정하자. 곡 하나 생기는 건 막아야지."
      },
      {
        "speaker": "world",
        "text": "좋아. 대신 네가 이기면 첫 소절은 같이 만들어 줘."
      }
    ],
    "bridge": "쟁반을 비우고 정원으로 나온 세계는 휴대폰을 꺼내 이번에는 만두 대신 사진 세 장을 내 앞에 놓았다."
  },
  {
    "id": "world-moment-05",
    "person": "world",
    "chapter": 2,
    "visit": 1,
    "title": "바람이 넘긴 페이지",
    "location": "roof",
    "lines": [
      {
        "speaker": "narrator",
        "text": "옥상 바람이 악보 한 장을 넘겼다. 세계는 붙잡는 대신 잠시 눈을 감았다."
      },
      {
        "speaker": "world",
        "text": "오늘은 아무것도 찍지 말자. 바람 소리는 기억으로도 남을 것 같아."
      },
      {
        "speaker": "player",
        "text": "그럼 박자만 맞춰 걸을까?"
      },
      {
        "speaker": "world",
        "text": "응. 근데 내가 느리게 가면 같이 느려져 줘."
      }
    ],
    "bridge": "악보를 가방에 넣고 옥상에서 내려온 우리는 촬영하는 사람이 없는 정원 벤치에 앉았다."
  },
  {
    "id": "world-moment-06",
    "person": "world",
    "chapter": 2,
    "visit": 2,
    "title": "책장 너머의 입모양",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "책장 너머에서 세계가 소리 없이 내 이름을 불렀다. 내가 대답하려 하자 입가에 손가락을 댔다."
      },
      {
        "speaker": "world",
        "text": "쉿. 이름 부른 건 난데 혼나는 건 네 쪽이겠다."
      },
      {
        "speaker": "player",
        "text": "입모양으로 부르는 건 반칙 아니야?"
      },
      {
        "speaker": "world",
        "text": "그럼 책 찾고 밖에서 불러 줘. 이번엔 내가 대답할게."
      }
    ],
    "bridge": "빌릴 책을 찾고 정원으로 나오자, 노래를 기다리던 세계의 시선이 먼저 내 어깨에 걸린 햇빛을 따라갔다."
  },
  {
    "id": "world-moment-07",
    "person": "world",
    "chapter": 3,
    "visit": 1,
    "title": "객석 끝까지 닿는 손",
    "location": "auditorium",
    "lines": [
      {
        "speaker": "narrator",
        "text": "객석 맨 뒤에서도 세계의 손이 보였다. 빈 의자들이 둘 사이를 길게 채웠다."
      },
      {
        "speaker": "world",
        "text": "이 정도면 보여? 네가 멀리 앉아도 내가 먼저 찾을 수 있게."
      },
      {
        "speaker": "player",
        "text": "보여. 이제 내려도 되는데."
      },
      {
        "speaker": "world",
        "text": "한 번만 더 흔들어 줘. 내가 제대로 찾은 건지 확인하게."
      }
    ],
    "bridge": "내 손을 확인한 세계가 밴드실까지 따라오라며 무대 인사 원고를 반으로 접었다."
  },
  {
    "id": "world-moment-08",
    "person": "world",
    "chapter": 3,
    "visit": 2,
    "title": "응원 글씨 밖의 별",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "세계는 응원 포스터 여백에 별을 하나 그렸다가 그 위에 더 큰 별을 덧그렸다."
      },
      {
        "speaker": "world",
        "text": "이건 번진 게 아니라 강조야. 그렇게 봐 줘."
      },
      {
        "speaker": "player",
        "text": "별 하나가 응원을 독점하는데?"
      },
      {
        "speaker": "world",
        "text": "오늘은 양보 안 해. 그래도 네 별 그릴 자리는 남겨 뒀어."
      }
    ],
    "bridge": "별을 그린 포스터를 말려 두고 연습실로 돌아오니, 세계가 펼친 곡 목록에도 작은 빈칸이 남아 있었다."
  },
  {
    "id": "world-moment-09",
    "person": "world",
    "chapter": 4,
    "visit": 1,
    "title": "빈칸을 찾은 복도",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "세계가 복도 게시판의 빈칸을 가리켰다. 다른 종이들이 빼곡한데 딱 그 자리만 비어 있었다."
      },
      {
        "speaker": "world",
        "text": "여기다 행사 사진 붙인대. 무대 사진만 잔뜩이면 재미없겠지?"
      },
      {
        "speaker": "player",
        "text": "준비하던 모습도 한 장 있으면 좋겠다."
      },
      {
        "speaker": "world",
        "text": "그럼 케이블 감다가 웃은 것도 후보. 멋있는 척 안 한 순간도 남겨 보자."
      }
    ],
    "bridge": "게시판에 붙일 사진은 나중에 고르기로 하고 밴드실로 들어가자, 세계는 녹화 중이던 기기부터 하나씩 껐다."
  },
  {
    "id": "world-moment-10",
    "person": "world",
    "chapter": 4,
    "visit": 2,
    "title": "우산 아래 빈자리",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정원 비가 잦아들어도 세계는 우산을 접지 않았다. 내 쪽으로 손잡이가 조금 기울었다."
      },
      {
        "speaker": "world",
        "text": "여긴 아직 비 와. 그러니까 잠깐 더 같이 가도 이상하진 않지?"
      },
      {
        "speaker": "player",
        "text": "핑계 없어도 같이 걸을 수 있어."
      },
      {
        "speaker": "world",
        "text": "알아. 그래도 이런 날씨는 조금 고맙네."
      }
    ],
    "bridge": "우산 끝에서 마지막 빗방울이 떨어질 즈음 우리는 정원을 지나 학교 뒤 산책로로 접어들었다."
  },
  {
    "id": "hyunsol-moment-01",
    "person": "hyunsol",
    "chapter": 0,
    "visit": 1,
    "title": "모형의 반대편",
    "location": "chemistry",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔은 벽에 걸린 분자 모형을 정면에서 보고는 옆으로 한 걸음 옮겼다."
      },
      {
        "speaker": "hyunsol",
        "text": "여기서 보면 겹친 게 따로 보여. 네 자리에서는 어떤 모양이야?"
      },
      {
        "speaker": "player",
        "text": "가운데 공이 하나 더 숨은 것 같은데."
      },
      {
        "speaker": "hyunsol",
        "text": "그럼 자리 바꿔 보자. 같은 걸 보고도 다른 말을 하는 이유부터 확인하게."
      }
    ],
    "bridge": "모형 주위를 한 바퀴 돈 현솔이 이번에는 실험대 끝의 밀봉된 전시병을 가리켰다."
  },
  {
    "id": "hyunsol-moment-02",
    "person": "hyunsol",
    "chapter": 0,
    "visit": 2,
    "title": "물뿌리개의 자리",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔이 정원 도구장의 물뿌리개를 크기별로 놓았다. 비어 있던 맨 끝 칸이 정확히 채워졌다."
      },
      {
        "speaker": "hyunsol",
        "text": "물을 다 비우고 넣어야 해. 내일 쓰는 사람 신발에 쏟아지면 억울하잖아."
      },
      {
        "speaker": "player",
        "text": "다음 사람이 누군지도 모르는데 꼼꼼하네."
      },
      {
        "speaker": "hyunsol",
        "text": "내일 내가 될 수도 있고, 네가 될 수도 있으니까. 손잡이 쪽은 네가 맞춰 줄래?"
      }
    ],
    "bridge": "물뿌리개 손잡이를 가지런히 맞춘 뒤 화학실로 돌아가니, 아직 자리를 정하지 못한 전시병 하나가 남아 있었다."
  },
  {
    "id": "hyunsol-moment-03",
    "person": "hyunsol",
    "chapter": 1,
    "visit": 1,
    "title": "공책 사이의 색",
    "location": "classroom",
    "lines": [
      {
        "speaker": "narrator",
        "text": "공책을 정리하던 현솔이 파란 표지 사이의 노란 공책을 꺼냈다. 내 것이었다."
      },
      {
        "speaker": "hyunsol",
        "text": "이건 네 거지? 색으로 나누다가 내용까지 같은 줄 알 뻔했어."
      },
      {
        "speaker": "player",
        "text": "표지가 너무 튀어서 바로 찾았네."
      },
      {
        "speaker": "hyunsol",
        "text": "응. 덕분에 네 메모를 펼칠 필요는 없었어. 읽어도 되는 건 네가 골라서 보여 줘."
      }
    ],
    "bridge": "노란 공책을 돌려받아 가방에 넣고 교실을 나서자 학생식당 쪽에서 익숙한 냄새가 올라왔다."
  },
  {
    "id": "hyunsol-moment-04",
    "person": "hyunsol",
    "chapter": 1,
    "visit": 2,
    "title": "달지 않은 정답",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔이 한입 먹고 잠깐 눈을 감았다. 평가는 쉽게 나오지 않았다."
      },
      {
        "speaker": "hyunsol",
        "text": "왜 이렇게 기다려. 네가 만든 것도 아니면서."
      },
      {
        "speaker": "player",
        "text": "네가 맛있게 먹으면 메뉴 고른 보람이 있잖아."
      },
      {
        "speaker": "hyunsol",
        "text": "합격. 근데 다음엔 네가 먹는 얼굴도 관찰할 거야."
      }
    ],
    "bridge": "현솔이 마지막 한입을 삼키고 식판 밑에서 꺼낸 것은 아직 답을 적지 못한 급식 설문지였다."
  },
  {
    "id": "hyunsol-moment-05",
    "person": "hyunsol",
    "chapter": 2,
    "visit": 1,
    "title": "책등에 남은 손끝",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔의 손이 추리소설 한 권에서 멈췄다. 실험 참고서를 찾는 줄 알았던 나는 책등을 다시 봤다."
      },
      {
        "speaker": "hyunsol",
        "text": "그런 표정 하지 마. 쉬는 시간까지 분자만 생각하진 않아."
      },
      {
        "speaker": "player",
        "text": "어떤 장면이 제일 좋아?"
      },
      {
        "speaker": "hyunsol",
        "text": "누가 정답을 말하기 전에, 둘이 같은 걸 다르게 봤다는 걸 아는 장면."
      }
    ],
    "bridge": "소설을 빌려 나온 나는 정원 벤치에 책을 내려놓았고, 현솔은 가방 옆의 종이컵 두 개를 내 쪽으로 당겼다."
  },
  {
    "id": "hyunsol-moment-06",
    "person": "hyunsol",
    "chapter": 2,
    "visit": 2,
    "title": "물웅덩이의 예외",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "산책로 물웅덩이를 피하려던 현솔이 돌 하나를 밟고 균형을 잡았다. 늘 정확하던 보폭이 엇나갔다."
      },
      {
        "speaker": "hyunsol",
        "text": "계산보다 돌이 미끄럽네."
      },
      {
        "speaker": "player",
        "text": "손 잡아 줄까?"
      },
      {
        "speaker": "hyunsol",
        "text": "지금은 웃지만 말고 옆에 있어 줘. 다음 발은 내가 고를게."
      }
    ],
    "bridge": "현솔이 마른 땅에 발을 내려놓은 뒤 함께 화학실로 돌아가 손을 씻고 전시용 설명 카드를 펼쳤다."
  },
  {
    "id": "hyunsol-moment-07",
    "person": "hyunsol",
    "chapter": 3,
    "visit": 1,
    "title": "정답보다 먼 빛",
    "location": "observatory",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔은 망원경에서 눈을 떼고 한동안 맨눈으로 하늘을 봤다."
      },
      {
        "speaker": "hyunsol",
        "text": "수치를 들으면 가까워질 줄 알았는데, 오히려 더 멀게 느껴져."
      },
      {
        "speaker": "player",
        "text": "그래서 실망했어?"
      },
      {
        "speaker": "hyunsol",
        "text": "아니. 다 안다고 생각 안 해도 되는 게 편해서. 네 얘기도 그럴 때가 있어."
      }
    ],
    "bridge": "관측을 마치고 교실로 돌아온 현솔은 하늘 이야기 대신 내게만 보여 줄 설명문 끝부분을 펼쳤다."
  },
  {
    "id": "hyunsol-moment-08",
    "person": "hyunsol",
    "chapter": 3,
    "visit": 2,
    "title": "작은 표식의 효용",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "현솔이 책상 위의 선에 노란 표식을 둘렀다. 연결하려고 집었던 선은 이미 옆으로 빼 두었다."
      },
      {
        "speaker": "hyunsol",
        "text": "모양이 같다고 용도까지 같진 않네. 오늘은 한 번에 외우려다 더 늦어졌어."
      },
      {
        "speaker": "player",
        "text": "그럼 다음 사람은 색을 먼저 보겠네."
      },
      {
        "speaker": "hyunsol",
        "text": "응. 나도 다음의 나를 너무 믿진 않으려고. 이 표식 떨어지는지만 같이 확인해 줘."
      }
    ],
    "bridge": "노란 표식이 붙은 선을 제자리에 꽂고 교실로 돌아오자 현솔이 책상 아래로 발표 연습 영상을 내밀었다."
  },
  {
    "id": "hyunsol-moment-09",
    "person": "hyunsol",
    "chapter": 4,
    "visit": 1,
    "title": "예보 밖의 약속",
    "location": "gate",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정문 처마 아래에서 현솔이 우산 끝의 물을 털었다. 손목시계를 보던 얼굴이 나를 보자 풀렸다."
      },
      {
        "speaker": "hyunsol",
        "text": "오늘은 비 예보보다 네 도착이 정확하네."
      },
      {
        "speaker": "player",
        "text": "기다리는 사람이 배고프면 오차가 안 된다며."
      },
      {
        "speaker": "hyunsol",
        "text": "기억했네. 메뉴는 걸으면서 정하자. 오늘은 계산기 안 켤 거야."
      }
    ],
    "bridge": "분식집으로 가기 전 정원 벤치에서 가방을 정리하던 현솔의 손에 계산기가 두 개 잡혔다."
  },
  {
    "id": "hyunsol-moment-10",
    "person": "hyunsol",
    "chapter": 4,
    "visit": 2,
    "title": "계산하지 않은 색",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "미술실에서 현솔이 색 두 개를 섞다가 붓을 멈췄다. 메모할 비율은 처음부터 없었다."
      },
      {
        "speaker": "hyunsol",
        "text": "같은 색 다시 만들라고 하면 못 할 것 같아."
      },
      {
        "speaker": "player",
        "text": "한 번만 나오는 색이어도 괜찮지 않아?"
      },
      {
        "speaker": "hyunsol",
        "text": "그럼 여기 남겨 두자. 오늘 네가 그렇게 말한 것도 같이 기억하게."
      }
    ],
    "bridge": "섞은 색이 마르도록 붓을 씻어 두고 정원으로 나온 현솔은 아무 용도도 적히지 않은 새 노트를 꺼냈다."
  },
  {
    "id": "taewoo-moment-01",
    "person": "taewoo",
    "chapter": 0,
    "visit": 1,
    "title": "바닥에 그린 첫 박자",
    "location": "dance",
    "lines": [
      {
        "speaker": "narrator",
        "text": "바닥에 붙은 테이프 두 줄 사이로 태우의 운동화가 미끄러졌다."
      },
      {
        "speaker": "taewoo",
        "text": "발만 보면 어려워져. 내가 옆으로 갈 때 어깨도 같이 봐."
      },
      {
        "speaker": "narrator",
        "text": "태우가 속도를 절반으로 낮췄다. 설명보다 먼저 내 쪽에 한 사람 자리가 생겼다."
      }
    ],
    "bridge": "태우 옆의 테이프 선에 발을 맞추자 음악이 멈추고 우리 둘의 카운트만 남았다."
  },
  {
    "id": "taewoo-moment-02",
    "person": "taewoo",
    "chapter": 0,
    "visit": 2,
    "title": "종이보다 빠른 손",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "복도 창문이 열리자 태우가 들고 있던 종이 한 장이 휙 들렸다."
      },
      {
        "speaker": "taewoo",
        "text": "잠깐, 그건 내가 외운 쪽이 아니야!"
      },
      {
        "speaker": "narrator",
        "text": "태우는 종이를 잡고 나서야 웃었다. 나는 남은 종이의 모서리를 눌러 주었다."
      }
    ],
    "bridge": "주운 종이를 파일에 끼워 연습실까지 가져오자 태우는 거울을 가릴 큰 천부터 펼쳤다."
  },
  {
    "id": "taewoo-moment-03",
    "person": "taewoo",
    "chapter": 1,
    "visit": 1,
    "title": "식기 전에 한마디",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "태우가 연습 얘기를 하다가 뜨거운 빵 앞에서 갑자기 조용해졌다."
      },
      {
        "speaker": "taewoo",
        "text": "아직 먹은 거 아니야. 뜨거운지 확인하는 중."
      },
      {
        "speaker": "narrator",
        "text": "박자는 빠르게 세던 사람이 이번 한입만큼은 오래 기다렸다."
      }
    ],
    "bridge": "간식을 먹고 쉬었다가 연습실에서 한 번 맞춰 보니, 마지막에 우리 발이 서로 다른 쪽을 향했다."
  },
  {
    "id": "taewoo-moment-04",
    "person": "taewoo",
    "chapter": 1,
    "visit": 2,
    "title": "다르게 묶은 두 색",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "산책로 벤치 앞에서 태우가 발걸음을 멈췄다. 두 운동화의 끈 색이 달랐다."
      },
      {
        "speaker": "taewoo",
        "text": "왼쪽은 자신 있게, 오른쪽은 안 다치게. 둘 다 중요하거든."
      },
      {
        "speaker": "narrator",
        "text": "매듭을 두 번 당긴 태우가 내 신발도 한번 확인했다."
      }
    ],
    "bridge": "다시 단단해진 매듭을 보니, 태우에게 그 두 색의 뜻을 처음 물었던 산책이 떠올랐다."
  },
  {
    "id": "taewoo-moment-05",
    "person": "taewoo",
    "chapter": 2,
    "visit": 1,
    "title": "멈춰 둔 한 프레임",
    "location": "media",
    "lines": [
      {
        "speaker": "narrator",
        "text": "미디어실 화면의 연습 영상이 한 발을 내딛기 직전에 멈췄다."
      },
      {
        "speaker": "taewoo",
        "text": "여기. 발보다 어깨가 먼저 움직이지? 내가 말로는 너무 빨리 설명했나 봐."
      },
      {
        "speaker": "narrator",
        "text": "재생 버튼을 누르기 전에 태우가 내 이해부터 기다렸다."
      }
    ],
    "bridge": "영상은 그 프레임에서 멈춰 두고 연습실로 돌아왔는데, 태우는 음악을 켜지 않고 벽 옆에 주저앉았다."
  },
  {
    "id": "taewoo-moment-06",
    "person": "taewoo",
    "chapter": 2,
    "visit": 2,
    "title": "내 박자를 빌려줄게",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "컴퓨터실에서 태우는 같은 구간을 세 번 들었다. 손가락만 책상 위를 바쁘게 뛰었다."
      },
      {
        "speaker": "taewoo",
        "text": "이상하다. 화면으로 박자를 보니까 오히려 헷갈려."
      },
      {
        "speaker": "narrator",
        "text": "내가 옆에서 박자를 세자 태우의 손가락이 잠시 쉬었다가 같은 지점에 닿았다."
      }
    ],
    "bridge": "헤드폰을 벗고 연습실에 도착한 태우가 방금 어려웠던 화면 대신 후배가 보낸 질문을 내게 보여 줬다."
  },
  {
    "id": "taewoo-moment-07",
    "person": "taewoo",
    "chapter": 3,
    "visit": 1,
    "title": "막 오르기 전의 별",
    "location": "auditorium",
    "lines": [
      {
        "speaker": "narrator",
        "text": "불이 반쯤 꺼진 강당에서 태우의 운동화 소리가 유난히 크게 들렸다."
      },
      {
        "speaker": "taewoo",
        "text": "사람 없을 때가 더 떨릴 때도 있어. 조용해서 내 생각만 들리거든."
      },
      {
        "speaker": "narrator",
        "text": "태우는 손안의 별 열쇠고리를 한번 쥐었다 펴고 객석 쪽을 바라봤다."
      }
    ],
    "bridge": "별을 쥔 손을 주머니에 넣은 태우가 무대 아래로 내려와 내가 앉을 객석 앞에서 멈췄다."
  },
  {
    "id": "taewoo-moment-08",
    "person": "taewoo",
    "chapter": 3,
    "visit": 2,
    "title": "삐뚤어도 알아볼 별",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "미술준비실에서 태우가 잘라 낸 별은 한쪽 팔이 유난히 길었다."
      },
      {
        "speaker": "taewoo",
        "text": "춤은 좌우 맞출 수 있는데 이건 왜 안 되지?"
      },
      {
        "speaker": "narrator",
        "text": "웃는 바람에 별도 흔들렸다. 반듯하지 않아도 태우가 만든 건 바로 알아볼 수 있었다."
      }
    ],
    "bridge": "새로 오린 별을 챙겨 강당에 도착하자, 태우가 가방에서 오래된 열쇠고리 하나를 따로 꺼냈다."
  },
  {
    "id": "taewoo-moment-09",
    "person": "taewoo",
    "chapter": 4,
    "visit": 1,
    "title": "우산 안의 보폭",
    "location": "gate",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정문 앞에서 태우가 우산을 펴고 빈 반쪽을 내 쪽으로 기울였다."
      },
      {
        "speaker": "taewoo",
        "text": "뛰면 너만 젖어. 오늘은 걷는 박자로 맞춰."
      },
      {
        "speaker": "narrator",
        "text": "태우의 보폭이 조금 작아졌다. 비가 그칠 때까지 급할 이유는 없었다."
      }
    ],
    "bridge": "비를 피해 강당으로 돌아온 태우가 우산을 접으며 조금 전 공연 때 내가 있던 객석을 다시 가리켰다."
  },
  {
    "id": "taewoo-moment-10",
    "person": "taewoo",
    "chapter": 4,
    "visit": 2,
    "title": "박수가 없는 쉬는 시간",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정원 벤치에 앉은 태우가 등받이에 팔을 포개고 턱을 얹었다."
      },
      {
        "speaker": "taewoo",
        "text": "오늘은 잘한 얘기 말고 별일 없는 얘기도 좀 해 줘."
      },
      {
        "speaker": "narrator",
        "text": "연습실에서의 큰 목소리 대신, 가까이 앉아야 들리는 말투가 남았다."
      }
    ],
    "bridge": "별일 없는 이야기를 한참 나눈 뒤 벤치에서 일어난 우리는 연습실을 지나쳐 정문 쪽으로 걸었다."
  },
  {
    "id": "taehun-moment-01",
    "person": "taehun",
    "chapter": 0,
    "visit": 1,
    "title": "구름의 다른 이름",
    "location": "roof",
    "lines": [
      {
        "speaker": "narrator",
        "text": "옥상 난간 안쪽에서 태훈이 구름 한 덩이를 가리켰다."
      },
      {
        "speaker": "taehun",
        "text": "도감의 이름은 적운인데, 오늘은 다른 이름도 하나 붙이고 싶어."
      },
      {
        "speaker": "narrator",
        "text": "내가 답하기도 전에 구름의 가장자리가 조금 달라졌다."
      }
    ],
    "bridge": "가리키던 구름이 흩어지자 태훈은 책을 안고 옥상 안쪽의 쉼터로 몇 걸음 옮겼다."
  },
  {
    "id": "taehun-moment-02",
    "person": "taehun",
    "chapter": 0,
    "visit": 2,
    "title": "책장 사이의 짧은 멈춤",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "도서관 반납 수레 앞에서 태훈이 책의 앞뒤를 번갈아 살폈다."
      },
      {
        "speaker": "taehun",
        "text": "첫 문장은 마음에 드는데 마지막 문장이 너무 궁금해서."
      },
      {
        "speaker": "narrator",
        "text": "태훈은 책을 덮지 않은 채 수레 옆의 통로를 조금 비켜 주었다."
      }
    ],
    "bridge": "책 수레가 지나가도록 길을 비킨 태훈은 반납할 책 안에서 빼지 못한 책갈피를 살짝 만졌다."
  },
  {
    "id": "taehun-moment-03",
    "person": "taehun",
    "chapter": 1,
    "visit": 1,
    "title": "반으로 나눈 별 모양",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "급식실에서 태훈이 고른 빵은 별 모양이었다. 한쪽 끝은 조금 눌려 있었다."
      },
      {
        "speaker": "taehun",
        "text": "실제 별은 이렇게 뾰족하지 않은데, 이쪽은 먹기 편하네."
      },
      {
        "speaker": "narrator",
        "text": "도감 얘기로 시작한 말이 결국 어느 쪽을 나눌지로 끝났다."
      }
    ],
    "bridge": "별 모양 빵을 나눠 먹고 도서관 앞에 도착했을 때 태훈은 책보다 먼저 잔뜩 흐려진 창밖을 확인했다."
  },
  {
    "id": "taehun-moment-04",
    "person": "taehun",
    "chapter": 1,
    "visit": 2,
    "title": "게시판 앞에서 멈춘 말",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "복도 게시판 앞에서 태훈이 관측 안내 종이를 한참 읽었다."
      },
      {
        "speaker": "taehun",
        "text": "이 그림만 보면 구름이 전부 같은 높이에 떠 있는 것 같네. 설명할 때 조심해야겠다."
      },
      {
        "speaker": "narrator",
        "text": "태훈이 관자놀이에 댔던 손을 내리고 노트에 작은 화살표를 더했다."
      }
    ],
    "bridge": "구름 그림 옆의 설명을 노트에 고쳐 적은 태훈이 도서관 반납함 앞에서는 전혀 다른 놀이를 제안했다."
  },
  {
    "id": "taehun-moment-05",
    "person": "taehun",
    "chapter": 2,
    "visit": 1,
    "title": "그림자를 재는 오후",
    "location": "classroom",
    "lines": [
      {
        "speaker": "narrator",
        "text": "빈 교실 책상 위에서 연필의 그림자가 자 한 칸을 조금 넘었다."
      },
      {
        "speaker": "taehun",
        "text": "같은 시간에 다시 재면 계절에 따라 달라져. 기다린 것도 기록이 되는 셈이야."
      },
      {
        "speaker": "narrator",
        "text": "태훈은 숫자 옆에 창밖 하늘을 작은 선으로 덧그렸다."
      }
    ],
    "bridge": "관측 도구를 정리하느라 뒤늦게 옥상에 올라가니 먼저 도착한 태훈이 하늘을 보던 고개를 돌렸다."
  },
  {
    "id": "taehun-moment-06",
    "person": "taehun",
    "chapter": 2,
    "visit": 2,
    "title": "돌 안에 남은 결",
    "location": "chemistry",
    "lines": [
      {
        "speaker": "narrator",
        "text": "과학실 표본함에서 꺼낸 돌에는 얇은 줄이 겹겹이 남아 있었다."
      },
      {
        "speaker": "taehun",
        "text": "여긴 광물이 배열된 방향이 보여. 그냥 줄무늬라고 적기엔 아깝지?"
      },
      {
        "speaker": "narrator",
        "text": "태훈이 돋보기를 내려놓고, 내가 직접 볼 수 있도록 표본을 돌려 주었다."
      }
    ],
    "bridge": "표본을 상자에 돌려놓은 태훈은 옥상에 올라서자 돋보기 대신 며칠 동안 모은 그림자 사진을 펼쳤다."
  },
  {
    "id": "taehun-moment-07",
    "person": "taehun",
    "chapter": 3,
    "visit": 1,
    "title": "덮개를 열기 전",
    "location": "observatory",
    "lines": [
      {
        "speaker": "narrator",
        "text": "관측실 망원경에는 아직 덮개가 씌워져 있었다. 태훈은 조작부에 손대지 않고 옆자리를 확인했다."
      },
      {
        "speaker": "taehun",
        "text": "선생님 오시면 시작하자. 기다리는 동안엔 여기 서 봐."
      },
      {
        "speaker": "narrator",
        "text": "태훈이 가리킨 곳에서는 창밖 하늘과 설명하는 얼굴이 함께 보였다."
      }
    ],
    "bridge": "선생님을 기다리며 관측실 창가에 나란히 선 태훈이 행사 뒤의 하늘부터 걱정하기 시작했다."
  },
  {
    "id": "taehun-moment-08",
    "person": "taehun",
    "chapter": 3,
    "visit": 2,
    "title": "예보의 빈칸",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "컴퓨터실 화면의 구름 표시가 한 줄 더 늘어났다. 태훈은 고개를 조금 기울였다."
      },
      {
        "speaker": "taehun",
        "text": "예보가 바뀌면 계획도 고치면 되지. 만날 사람까지 바꾸는 건 아니고."
      },
      {
        "speaker": "narrator",
        "text": "노트 한쪽에 지우개 자국이 생겼고, 그 옆에 새 장소를 적을 여백이 남았다."
      }
    ],
    "bridge": "바뀐 예보를 적고 컴퓨터를 끈 우리는 관측실에 들러 하늘을 볼 자리를 미리 확인하기로 했다."
  },
  {
    "id": "taehun-moment-09",
    "person": "taehun",
    "chapter": 4,
    "visit": 1,
    "title": "아직 봉하지 않은 문장",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "산책로를 걷는 동안 태훈은 봉투를 끝내 접어 닫지 않았다."
      },
      {
        "speaker": "taehun",
        "text": "쓰고 나면 끝날 줄 알았는데, 같이 읽을 자리도 남겨야겠더라."
      },
      {
        "speaker": "narrator",
        "text": "발걸음이 느려질 때마다 봉투 안의 종이가 작게 바스락거렸다."
      }
    ],
    "bridge": "봉투를 책 사이에 끼우던 태훈의 휴대폰에 관측회 안내가 도착했지만, 산책로에서의 발걸음은 멈추지 않았다."
  },
  {
    "id": "taehun-moment-10",
    "person": "taehun",
    "chapter": 4,
    "visit": 2,
    "title": "작은 돌의 자리",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정원에서 태훈이 작은 돌 하나를 노트 끝에 얹었다."
      },
      {
        "speaker": "taehun",
        "text": "표본으로 가져가진 않을 거야. 지금은 책장만 잠깐 맡기는 거지."
      },
      {
        "speaker": "narrator",
        "text": "돌을 제자리에 돌려놓을 때까지, 우리는 다음 문장을 천천히 골랐다."
      }
    ],
    "bridge": "작은 돌을 화단 옆에 돌려놓고 산책로로 나온 태훈은 노트 대신 아직 이름이 없는 봉투를 꺼냈다."
  },
  {
    "id": "seoyul-moment-01",
    "person": "seoyul",
    "chapter": 0,
    "visit": 1,
    "title": "꽃 옆의 빈칸",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "화단 앞에서 서율이 색종이 세 장을 번갈아 들고 있었다."
      },
      {
        "speaker": "seoyul",
        "text": "꽃을 그리려는데 노랑 하나로는 안 되네. 그림자 쪽은 거의 초록이야."
      },
      {
        "speaker": "player",
        "text": "꽃은 그대로 두고, 종이만 바꿔 보는 거구나."
      },
      {
        "speaker": "seoyul",
        "text": "응. 네 눈에는 어느 쪽이 더 가까워? 미술실 가기 전에 골라 보자."
      }
    ],
    "bridge": "고른 색종이를 들고 미술실에 도착하자 서율은 말리고 있는 포스터 옆의 빈 의자를 내 쪽으로 돌렸다."
  },
  {
    "id": "seoyul-moment-02",
    "person": "seoyul",
    "chapter": 0,
    "visit": 2,
    "title": "손끝에 걸린 화집",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "도서관 사다리 발판에서 서율이 커다란 화집을 품에 안았다."
      },
      {
        "speaker": "seoyul",
        "text": "표지는 얇아 보였는데, 들고 오니까 벽돌이네."
      },
      {
        "speaker": "player",
        "text": "책부터 받을게. 내려오는 건 천천히 해."
      },
      {
        "speaker": "seoyul",
        "text": "고마워. 이 무게만큼 좋은 그림이 들어 있으면 좋겠다."
      }
    ],
    "bridge": "화집을 함께 미술실 작업대까지 옮겨 놓자 서율이 책 속 인물 대신 자신을 가리켰다."
  },
  {
    "id": "seoyul-moment-03",
    "person": "seoyul",
    "chapter": 1,
    "visit": 1,
    "title": "웃다가 놓친 한 박자",
    "location": "band",
    "lines": [
      {
        "speaker": "narrator",
        "text": "서율이 반주를 하다 갑자기 손을 번쩍 들었다. 마지막 음만 혼자 길게 남았다."
      },
      {
        "speaker": "seoyul",
        "text": "잠깐. 네가 발로 세는 박자가 너무 진지해서 못 참겠어."
      },
      {
        "speaker": "player",
        "text": "진지하게 틀리고 있었는데."
      },
      {
        "speaker": "seoyul",
        "text": "그건 나도야. 다시 할 때는 서로 얼굴 보지 말자."
      }
    ],
    "bridge": "웃음이 잦아들자 서율은 긴 여운을 남긴 건반에서 손을 떼고 내가 누를 음 하나를 짚었다."
  },
  {
    "id": "seoyul-moment-04",
    "person": "seoyul",
    "chapter": 1,
    "visit": 2,
    "title": "바람이 고른 자리",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "복도 창문이 열리자 서율의 종이 장식 하나가 파일 밖으로 날아갔다."
      },
      {
        "speaker": "seoyul",
        "text": "저기, 꽃 모양! 바닥에 닿기 전에 잡아 줘."
      },
      {
        "speaker": "player",
        "text": "잡았어. 원래 붙이려던 자리보다 멀리 왔네."
      },
      {
        "speaker": "seoyul",
        "text": "그러게. 저 창가에 걸면 흔들리는 것도 그림이 되겠다."
      }
    ],
    "bridge": "날아간 장식을 파일 안에 넣고 밴드실로 들어온 서율이 색종이보다 먼저 짧은 곡 하나를 틀었다."
  },
  {
    "id": "seoyul-moment-05",
    "person": "seoyul",
    "chapter": 2,
    "visit": 1,
    "title": "손가락으로 자른 하늘",
    "location": "roof",
    "lines": [
      {
        "speaker": "narrator",
        "text": "옥상에서 서율은 손가락으로 작은 사각형을 만들고 하늘을 잘라 보고 있었다."
      },
      {
        "speaker": "seoyul",
        "text": "여기만 그리면 조용한데, 저 안테나까지 넣으면 좀 외로워져."
      },
      {
        "speaker": "player",
        "text": "같은 하늘인데 모서리가 분위기를 바꾸네."
      },
      {
        "speaker": "seoyul",
        "text": "네가 고르면 어디까지 넣을지 궁금하다. 내 손 말고 네 손으로 해 봐."
      }
    ],
    "bridge": "손가락 사각형 안에 넣었던 하늘을 떠올리며 미술실에 뒤늦게 들어서니 서율의 그림에는 의자 한쪽만 비어 있었다."
  },
  {
    "id": "seoyul-moment-06",
    "person": "seoyul",
    "chapter": 2,
    "visit": 2,
    "title": "컵에 남은 표정",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "서율이 빈 종이컵을 돌려 가며 아주 작은 눈 두 개를 그렸다."
      },
      {
        "speaker": "seoyul",
        "text": "너 아까 국 뜨거워서 이런 얼굴 했어."
      },
      {
        "speaker": "player",
        "text": "눈이 이렇게까지 몰리지는 않았을 텐데."
      },
      {
        "speaker": "seoyul",
        "text": "그건 컵이 좁아서 그래. 버리기 전에 한 번만 더 웃어 줘."
      }
    ],
    "bridge": "종이컵의 얼굴을 사진으로 남기고 미술실에 돌아오자 서율이 작업대 아래의 낡은 그림 상자를 끌어냈다."
  },
  {
    "id": "seoyul-moment-07",
    "person": "seoyul",
    "chapter": 3,
    "visit": 1,
    "title": "무대 끝의 작은 표시",
    "location": "auditorium",
    "lines": [
      {
        "speaker": "narrator",
        "text": "서율이 무대 가장자리의 색 테이프를 꾹 눌렀다. 구겨진 끝이 쉽게 붙지 않았다."
      },
      {
        "speaker": "seoyul",
        "text": "이 표시가 들뜨면 조명 받을 때 괜히 반짝여."
      },
      {
        "speaker": "player",
        "text": "이쪽 끝은 내가 잡을게. 네 쪽부터 천천히 붙여 봐."
      },
      {
        "speaker": "seoyul",
        "text": "됐다. 멀리서는 안 보여도, 가까이서 보면 우리가 같이 한 자리네."
      }
    ],
    "bridge": "강당 테이프 정리를 끝내고 산책로에 나온 서율은 내 소매를 힐끗 본 뒤 스케치북을 가슴 쪽으로 당겼다."
  },
  {
    "id": "seoyul-moment-08",
    "person": "seoyul",
    "chapter": 3,
    "visit": 2,
    "title": "비가 멈추는 동안",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "산책로 처마 아래에서 서율이 스케치북을 안쪽으로 감싸 안았다."
      },
      {
        "speaker": "seoyul",
        "text": "비 오는 색은 좋아하는데, 종이가 젖는 건 싫네."
      },
      {
        "speaker": "player",
        "text": "그럼 멈출 때까지 눈으로만 그려 둘까?"
      },
      {
        "speaker": "seoyul",
        "text": "응. 네가 기억하는 색도 나중에 말해 줘. 나는 자꾸 파란 쪽만 보니까."
      }
    ],
    "bridge": "비가 가늘어져 처마를 벗어나자 서율이 젖지 않게 끼워 둔 초대장 한 장을 스케치북에서 꺼냈다."
  },
  {
    "id": "seoyul-moment-09",
    "person": "seoyul",
    "chapter": 4,
    "visit": 1,
    "title": "바닥에 펼친 다음 장",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "미술실 바닥에 펼친 그림들 사이로 서율이 빈 종이 한 장을 밀어 넣었다."
      },
      {
        "speaker": "seoyul",
        "text": "완성한 것만 늘어놓으니까 숨 쉴 데가 없어서."
      },
      {
        "speaker": "player",
        "text": "아무것도 없는 종이도 전시하는 거야?"
      },
      {
        "speaker": "seoyul",
        "text": "다음에 그릴 자리. 이건 네가 먼저 한 줄 그어도 돼."
      }
    ],
    "bridge": "빈 종이는 다음을 위해 남겨 둔 서율이 바닥에 펼친 그림들 사이에서 다른 한 장을 조심스럽게 골랐다."
  },
  {
    "id": "seoyul-moment-10",
    "person": "seoyul",
    "chapter": 4,
    "visit": 2,
    "title": "문밖에서 돌아본 얼굴",
    "location": "gate",
    "lines": [
      {
        "speaker": "narrator",
        "text": "교문을 먼저 나선 서율이 몇 걸음 뒤에서 다시 돌아봤다."
      },
      {
        "speaker": "seoyul",
        "text": "아, 이거. 가방에 넣어 두면 또 잊을 것 같아서."
      },
      {
        "speaker": "player",
        "text": "접힌 종이에 그림부터 보이네."
      },
      {
        "speaker": "seoyul",
        "text": "빈칸은 같이 정하려고 남겼어. 걸으면서 펼쳐 볼래?"
      }
    ],
    "bridge": "접힌 그림에 어울릴 테두리를 골라 보려고 우리는 교문 안으로 돌아가 미술실 작업대 앞에 섰다."
  },
  {
    "id": "juhan-moment-01",
    "person": "juhan",
    "chapter": 0,
    "visit": 1,
    "title": "화면 밖의 길잡이",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "주한이 화면 대신 종이에 그린 네모들을 연필 끝으로 짚었다."
      },
      {
        "speaker": "juhan",
        "text": "이 길, 만든 나는 바로 찾는데 처음 보는 사람은 다르게 보겠지?"
      },
      {
        "speaker": "player",
        "text": "여기서 두 번 돌아가는 줄 알았어."
      },
      {
        "speaker": "juhan",
        "text": "그거 적어 둬야겠다. 네가 헤맨 자리가 내 설명이 비어 있던 곳이네."
      }
    ],
    "bridge": "내가 헤맨 길에 작은 표시를 남긴 주한이 종이 미로를 치우고 컴퓨터의 방향키 쪽으로 의자를 밀었다."
  },
  {
    "id": "juhan-moment-02",
    "person": "juhan",
    "chapter": 0,
    "visit": 2,
    "title": "책장 사이의 우회로",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "책장 사이로 주한이 책을 이리저리 기울이는 모습이 보였다."
      },
      {
        "speaker": "juhan",
        "text": "코드를 읽는 게 이것보다 쉽겠어. 접힌 선은 앞뒤가 다르네."
      },
      {
        "speaker": "player",
        "text": "책을 거꾸로 보면 조금 나아져?"
      },
      {
        "speaker": "juhan",
        "text": "아니. 네가 반대쪽에서 봐 주면 나을 것 같아서 기다렸어."
      }
    ],
    "bridge": "팝업북을 반납하고 컴퓨터실로 돌아오는 길에 주한은 종이 장치보다 훨씬 서툴렀던 자신의 첫 게임을 떠올렸다."
  },
  {
    "id": "juhan-moment-03",
    "person": "juhan",
    "chapter": 1,
    "visit": 1,
    "title": "맞히기 전에 웃는 맛",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "쿠키 맛을 설명하려던 주한이 먼저 입을 가렸다. 아직 한 입을 다 삼키지 못한 참이었다."
      },
      {
        "speaker": "player",
        "text": "정답은 천천히 말해도 돼."
      },
      {
        "speaker": "juhan",
        "text": "맛 맞히기보다 먹는 속도가 빨랐네. 잠깐만."
      },
      {
        "speaker": "narrator",
        "text": "주한은 빈 포장지를 뒤집어 놓고, 남은 조각을 내 쪽으로 밀었다."
      }
    ],
    "bridge": "쿠키 가루를 털고 컴퓨터실로 돌아온 주한은 이번에는 입을 가리는 대신 화면의 마지막 문장을 가리켰다."
  },
  {
    "id": "juhan-moment-04",
    "person": "juhan",
    "chapter": 1,
    "visit": 2,
    "title": "휴식에도 돌발 상황",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "주한이 간식 봉투를 여는 순간 냅킨이 바람을 타고 벤치를 벗어났다."
      },
      {
        "speaker": "juhan",
        "text": "잠깐, 휴식 계획에는 추격전 없었는데!"
      },
      {
        "speaker": "player",
        "text": "내 쪽으로 오고 있어. 길만 막을게."
      },
      {
        "speaker": "juhan",
        "text": "잡았다. 오늘은 화면 밖에서도 둘이 움직여야 되는 날이네."
      }
    ],
    "bridge": "붙잡은 냅킨을 간식 봉투 밑에 눌러 둔 주한이 정원 벤치에 앉아 휴대폰 화면을 뒤집었다."
  },
  {
    "id": "juhan-moment-05",
    "person": "juhan",
    "chapter": 2,
    "visit": 1,
    "title": "접힌 선의 새 용도",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "주한이 종이 상자의 한쪽 모서리를 누를 때마다 반대쪽이 벌어졌다."
      },
      {
        "speaker": "juhan",
        "text": "한 군데 고치면 다른 데가 무너지는 건 익숙한데, 종이는 저장도 안 되네."
      },
      {
        "speaker": "player",
        "text": "바닥을 받쳐 줄게. 모서리는 네가 잡아 봐."
      },
      {
        "speaker": "juhan",
        "text": "오, 서 있다. 지금 손 놓지 마. 나도 잠깐 성공한 모양을 보고 싶어."
      }
    ],
    "bridge": "겨우 세운 종이 상자를 선반에 올려 두고 컴퓨터실로 돌아오자 주한이 두 번째 조작기를 내 자리 앞에 놓았다."
  },
  {
    "id": "juhan-moment-06",
    "person": "juhan",
    "chapter": 2,
    "visit": 2,
    "title": "손으로 만든 대사",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "복도 벽에 토끼처럼 생긴 그림자가 나타났다가 손가락을 접자 금방 작아졌다."
      },
      {
        "speaker": "juhan",
        "text": "화면 없이 움직이는 캐릭터. 기능은 귀 접기 하나야."
      },
      {
        "speaker": "player",
        "text": "내 그림자는 자꾸 집게가 되는데."
      },
      {
        "speaker": "juhan",
        "text": "그럼 집게도 등장시키자. 토끼 혼자 있으면 할 얘기가 없으니까."
      }
    ],
    "bridge": "손 그림자를 접고 미술실에 들어선 주한은 이번에는 빛이 아니라 자투리 종이를 접어 보기로 했다."
  },
  {
    "id": "juhan-moment-07",
    "person": "juhan",
    "chapter": 3,
    "visit": 1,
    "title": "녹음 버튼 앞의 숨",
    "location": "media",
    "lines": [
      {
        "speaker": "narrator",
        "text": "미디어실에서 주한이 녹음 버튼 앞에 손을 멈췄다."
      },
      {
        "speaker": "juhan",
        "text": "프로그램 인사말을 내 목소리로 넣어 보려는데, 글자로 쓸 때랑 다르네."
      },
      {
        "speaker": "player",
        "text": "내가 듣는 쪽에 있을게. 첫 문장만 해 봐."
      },
      {
        "speaker": "juhan",
        "text": "응. 잘 읽는 것 말고, 한 사람한테 말하는 것부터 해 볼게."
      }
    ],
    "bridge": "한 사람에게 건넬 목소리를 녹음한 뒤 컴퓨터실에서 시연을 마치자 주한의 손이 종료 버튼 위에 머물렀다."
  },
  {
    "id": "juhan-moment-08",
    "person": "juhan",
    "chapter": 3,
    "visit": 2,
    "title": "작은 렌즈의 바깥",
    "location": "roof",
    "lines": [
      {
        "speaker": "narrator",
        "text": "주한이 작은 카메라를 내렸다. 화면에는 아직 하늘만 어둡게 찍혀 있었다."
      },
      {
        "speaker": "juhan",
        "text": "눈으로는 보이는데 사진에는 안 나오네."
      },
      {
        "speaker": "player",
        "text": "저 건물 위에 하나. 나도 보여."
      },
      {
        "speaker": "juhan",
        "text": "그럼 기록은 둘이 봤다는 걸로 됐다. 오늘은 저장 안 해도 되겠어."
      }
    ],
    "bridge": "하늘 사진은 저장하지 않은 채 옥상에서 내려온 주한이 컴퓨터실 화면 한쪽의 작은 알림 창을 열었다."
  },
  {
    "id": "juhan-moment-09",
    "person": "juhan",
    "chapter": 4,
    "visit": 1,
    "title": "지운 자리의 여유",
    "location": "classroom",
    "lines": [
      {
        "speaker": "narrator",
        "text": "칠판을 다 지운 주한이 분필 가루 묻은 손을 내려다봤다."
      },
      {
        "speaker": "juhan",
        "text": "깔끔해졌는데 손에 오늘 한 일이 남았네."
      },
      {
        "speaker": "player",
        "text": "천 여기 있어. 왼쪽 모서리는 내가 마저 지울게."
      },
      {
        "speaker": "juhan",
        "text": "고마워. 다 끝내고 나면 뭘 고칠지 말고, 어디 갈지 생각하고 싶다."
      }
    ],
    "bridge": "분필 가루를 씻고 컴퓨터실에 도착하자 주한은 수정할 코드 대신 같이 놀 게임부터 실행했다."
  },
  {
    "id": "juhan-moment-10",
    "person": "juhan",
    "chapter": 4,
    "visit": 2,
    "title": "다음 화면 대신 산책",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "주한이 산책로에서 걸음을 조금 늦췄다. 평소보다 손이 한가로워 보였다."
      },
      {
        "speaker": "juhan",
        "text": "아무것도 안 들고 나오니까 자꾸 손 둘 데를 찾게 되네."
      },
      {
        "speaker": "player",
        "text": "오늘은 빈손으로 계속 걸어도 되잖아."
      },
      {
        "speaker": "juhan",
        "text": "응. 그럼 다음에 할 일은 돌아가서 정하자. 지금은 이쪽 길이 궁금해."
      }
    ],
    "bridge": "산책로를 한 바퀴 더 돈 뒤 돌아온 컴퓨터실에는 주한이 닫지 않은 게임의 첫 화면이 남아 있었다."
  },
  {
    "id": "minhyuk-moment-01",
    "person": "minhyuk",
    "chapter": 0,
    "visit": 1,
    "title": "복도의 한 뼘",
    "location": "hallway",
    "lines": [
      {
        "speaker": "narrator",
        "text": "복도에 민혁이 붙인 테이프 두 줄이 길게 이어져 있었다."
      },
      {
        "speaker": "minhyuk",
        "text": "장비를 옮겨도 지나갈 자리는 남겠지? 네가 저쪽에서 걸어와 봐."
      },
      {
        "speaker": "narrator",
        "text": "나는 두 줄 사이를 걸었다. 민혁은 자를 접고 나서야 고개를 끄덕였다."
      }
    ],
    "bridge": "복도 테이프를 정리하고 정문에 이르렀을 때 빗소리가 굵어지자 민혁은 내 손에 우산이 없는 걸 먼저 알아봤다."
  },
  {
    "id": "minhyuk-moment-02",
    "person": "minhyuk",
    "chapter": 0,
    "visit": 2,
    "title": "반장의 빈자리",
    "location": "classroom",
    "lines": [
      {
        "speaker": "narrator",
        "text": "자리는 맞춰 놓고도 민혁은 의자 하나를 옮겼다 다시 놓았다."
      },
      {
        "speaker": "minhyuk",
        "text": "여기 앉으면 칠판이 가려지네. 줄은 반듯한데, 그게 다는 아니었어."
      },
      {
        "speaker": "narrator",
        "text": "나는 옆줄 의자를 비켰다. 그녀가 비어 있는 시야를 확인하며 웃음을 흘렸다."
      }
    ],
    "bridge": "옮긴 의자를 밀어 넣은 민혁이 교실 뒤에 말려 두었던 우산 손잡이에서 젖었다 마른 종이를 떼어 냈다."
  },
  {
    "id": "minhyuk-moment-03",
    "person": "minhyuk",
    "chapter": 1,
    "visit": 1,
    "title": "도망가는 귤",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "급식판 위의 귤이 굴러갔다. 민혁의 손바닥이 탁, 그 앞을 막았다."
      },
      {
        "speaker": "minhyuk",
        "text": "출구는 그쪽이 아닙니다. ……아, 귤한테 말했네."
      },
      {
        "speaker": "narrator",
        "text": "나는 웃음을 참다 실패했다. 민혁도 결국 어깨를 들썩였다."
      }
    ],
    "bridge": "귤이 다시 구르지 않게 쟁반 한쪽에 놓은 민혁은 식탁 위 목록의 마지막 칸에 표시를 했다."
  },
  {
    "id": "minhyuk-moment-04",
    "person": "minhyuk",
    "chapter": 1,
    "visit": 2,
    "title": "휘어진 팻말",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "기울어진 화단 팻말을 민혁이 조심스럽게 세웠다."
      },
      {
        "speaker": "minhyuk",
        "text": "꽉 누르면 뿌리 다칠 수도 있겠다. 흙 조금만 잡아 줄래?"
      },
      {
        "speaker": "narrator",
        "text": "내가 흙을 받치는 동안 그녀는 힘을 풀었다. 반듯함보다 먼저 살펴야 할 것이 있었다."
      }
    ],
    "bridge": "화단 팻말을 세우고 손을 씻어 식당에 앉으니 민혁이 휴대폰에 띄운 두 자리 사진을 번갈아 확대했다."
  },
  {
    "id": "minhyuk-moment-05",
    "person": "minhyuk",
    "chapter": 2,
    "visit": 1,
    "title": "반납은 천천히",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "조용한 도서관에 수레 바퀴 소리가 유난히 크게 울렸다."
      },
      {
        "speaker": "minhyuk",
        "text": "쉿…… 내가 낸 소리야. 미안. 이번에는 아주 천천히 갈게."
      },
      {
        "speaker": "narrator",
        "text": "민혁은 책보다 느리게 발을 옮겼다. 나는 앞에서 수레가 지날 틈을 만들었다."
      }
    ],
    "bridge": "수레를 정리한 뒤 잠시 헤어졌다가 점심에 식당에서 다시 만났을 때 민혁은 아직 식사를 시작하지 않고 있었다."
  },
  {
    "id": "minhyuk-moment-06",
    "person": "minhyuk",
    "chapter": 2,
    "visit": 2,
    "title": "접히지 않는 바람",
    "location": "roof",
    "lines": [
      {
        "speaker": "narrator",
        "text": "옥상 바람은 민혁의 계획표를 아무렇게나 넘겼다."
      },
      {
        "speaker": "minhyuk",
        "text": "잠깐, 아직 그 페이지 아니야. 종이까지 먼저 가려고 하네."
      },
      {
        "speaker": "narrator",
        "text": "나는 노트 귀퉁이를 눌렀다. 바람이 멈추자 그녀가 긴 숨을 내쉬었다."
      }
    ],
    "bridge": "바람이 센 옥상에서 내려와 정원에 앉았는데도 민혁의 손에는 계획표 대신 출석부가 남아 있었다."
  },
  {
    "id": "minhyuk-moment-07",
    "person": "minhyuk",
    "chapter": 3,
    "visit": 1,
    "title": "마침표 하나",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "민혁이 안내문 마지막 줄을 고친 뒤 커서 앞에서 멈췄다."
      },
      {
        "speaker": "minhyuk",
        "text": "명령처럼 들리지 않아? 꼭 필요한 말만 남겼는데도 어렵다."
      },
      {
        "speaker": "narrator",
        "text": "나는 문장 끝을 함께 읽었다. 민혁은 느낌표를 지우고 마침표를 찍었다."
      }
    ],
    "bridge": "안내문을 저장하고 교실로 돌아온 민혁이 모두에게 보낼 종이는 덮고 자기 일정표만 펼쳤다."
  },
  {
    "id": "minhyuk-moment-08",
    "person": "minhyuk",
    "chapter": 3,
    "visit": 2,
    "title": "객석 앞의 연습",
    "location": "auditorium",
    "lines": [
      {
        "speaker": "narrator",
        "text": "몇 명만 앉아 있는 객석을 향해 민혁이 인사했다. 목소리 끝이 살짝 떨렸다."
      },
      {
        "speaker": "minhyuk",
        "text": "진행 순서는 외웠어. 그런데 얼굴이 보이면 다 잊을까 봐."
      },
      {
        "speaker": "narrator",
        "text": "나는 앞줄에서 고개를 끄덕였다. 다시 인사할 때 민혁은 조금 천천히 숨을 골랐다."
      }
    ],
    "bridge": "인사 연습이 끝나 교실로 돌아오자 민혁은 새 완장을 팔에 대 보다가 뻣뻣한 끈을 내려다봤다."
  },
  {
    "id": "minhyuk-moment-09",
    "person": "minhyuk",
    "chapter": 4,
    "visit": 1,
    "title": "걸음을 늦추는 일",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "정문 쪽으로 바삐 걷던 민혁이 뒤를 돌아봤다. 내가 벤치 옆에 멈춰 있었기 때문이다."
      },
      {
        "speaker": "minhyuk",
        "text": "아, 오늘은 서둘러야 하는 날 아니지. 습관이 무섭네."
      },
      {
        "speaker": "narrator",
        "text": "민혁이 내 옆까지 되돌아왔다. 다음 걸음부터는 둘의 속도가 같았다."
      }
    ],
    "bridge": "같은 속도로 정문에 도착한 민혁은 교문 기둥 옆에서 멈춰 팔에 남아 있던 완장 매듭을 풀었다."
  },
  {
    "id": "minhyuk-moment-10",
    "person": "minhyuk",
    "chapter": 4,
    "visit": 2,
    "title": "반듯하지 않은 별",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "민혁이 만든 종이 별은 꼭짓점 하나가 유난히 짧았다."
      },
      {
        "speaker": "minhyuk",
        "text": "새로 자를까 했는데…… 이쪽이 더 기억나겠지?"
      },
      {
        "speaker": "narrator",
        "text": "나는 고개를 끄덕였다. 그녀는 그 별을 버릴 종이 더미에서 꺼내 놓았다."
      }
    ],
    "bridge": "버리지 않기로 한 종이 별을 파일에 넣어 교문까지 들고 나온 민혁이 행사 사진에서 다른 작은 기억을 찾아냈다."
  },
  {
    "id": "junyeon-moment-01",
    "person": "junyeon",
    "chapter": 0,
    "visit": 1,
    "title": "칠판의 여백",
    "location": "classroom",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연은 칠판 가장자리에 작은 네모를 그렸다."
      },
      {
        "speaker": "junyeon",
        "text": "여기에 준비물 적으면 어때? 그림은 잘 못 그려도 네모는 그릴 수 있어."
      },
      {
        "speaker": "narrator",
        "text": "나는 지우개로 삐져나온 선을 닦았다. 준연이 빈칸의 크기를 다시 재봤다."
      }
    ],
    "bridge": "칠판 네모 안에 적을 준비물을 확인하고 나니 교실 앞 책상에 옮겨야 할 묶음이 쌓여 있었다."
  },
  {
    "id": "junyeon-moment-02",
    "person": "junyeon",
    "chapter": 0,
    "visit": 2,
    "title": "마른 자리",
    "location": "chemistry",
    "lines": [
      {
        "speaker": "narrator",
        "text": "세척을 마친 비커를 준연이 한 개씩 건조대에 올렸다."
      },
      {
        "speaker": "junyeon",
        "text": "가까이 붙이면 잘 안 마른대. 이 정도 띄워 놓을까?"
      },
      {
        "speaker": "narrator",
        "text": "나는 마른 받침을 옆에 놓았다. 유리가 부딪히지 않게 두 사람의 손이 번갈아 움직였다."
      }
    ],
    "bridge": "비커 간격을 다시 확인하고 교실로 돌아온 준연은 공책을 꺼내 지우개 자국이 많은 계산 쪽을 펼쳤다."
  },
  {
    "id": "junyeon-moment-03",
    "person": "junyeon",
    "chapter": 1,
    "visit": 1,
    "title": "반납하는 오후",
    "location": "library",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연이 빌린 책을 반납대 위에 차례로 올렸다."
      },
      {
        "speaker": "junyeon",
        "text": "기한 넘길까 봐 계속 가방에 넣어 뒀어. 무거운 줄도 몰랐네."
      },
      {
        "speaker": "narrator",
        "text": "나는 마지막 책이 기울지 않게 받쳤다. 빈 가방을 멘 준연의 어깨가 조금 내려갔다."
      }
    ],
    "bridge": "가벼워진 가방을 메고 도서관에서 정원까지 걸어온 준연은 가방에 남아 있던 작은 일정표를 꺼냈다."
  },
  {
    "id": "junyeon-moment-04",
    "person": "junyeon",
    "chapter": 1,
    "visit": 2,
    "title": "눈높이의 꽃",
    "location": "garden",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연은 화단 앞 벤치에 앉아 꽃잎의 모양을 비교했다."
      },
      {
        "speaker": "junyeon",
        "text": "같은 꽃인데 다 조금씩 달라. 그린 사람이 따로 있는 것 같아."
      },
      {
        "speaker": "narrator",
        "text": "나는 휴대폰 대신 눈으로 차이를 찾아봤다. 준연이 가장 작은 꽃을 가리켰다."
      }
    ],
    "bridge": "꽃잎마다 다른 모양을 찾던 준연의 손이 무릎 위 조 편성표로 내려오더니 이름이 적힌 칸에서 멈췄다."
  },
  {
    "id": "junyeon-moment-05",
    "person": "junyeon",
    "chapter": 2,
    "visit": 1,
    "title": "아직 따뜻한 자리",
    "location": "cafeteria",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연이 식판을 든 채 빈 의자 앞에 멈췄다."
      },
      {
        "speaker": "junyeon",
        "text": "여기…… 누가 맡아 둔 거 아니지? 가방 없어서."
      },
      {
        "speaker": "narrator",
        "text": "나는 옆 의자를 당겼다. 준연은 국그릇이 흔들리지 않게 천천히 앉았다."
      }
    ],
    "bridge": "점심을 먹고 각자 볼일을 마친 뒤 나는 정원을 지나다가 준연이 앉아 있는 벤치 앞에서 다시 멈췄다."
  },
  {
    "id": "junyeon-moment-06",
    "person": "junyeon",
    "chapter": 2,
    "visit": 2,
    "title": "소리를 맞추는 손",
    "location": "media",
    "lines": [
      {
        "speaker": "narrator",
        "text": "녹음 음량이 갑자기 커지자 준연이 조절 손잡이를 조금 내렸다."
      },
      {
        "speaker": "junyeon",
        "text": "한 칸만 옮겨도 확 달라지네. 이 정도면 말소리가 잘 들려?"
      },
      {
        "speaker": "narrator",
        "text": "나는 고개를 끄덕였다. 그녀는 같은 구간을 다시 들어 보고 손을 뗐다."
      }
    ],
    "bridge": "녹음 음량을 맞추고 정원에서 쉬던 준연이 가방에 달린 행사 명찰을 뒤집어 빈 뒷면을 보여 줬다."
  },
  {
    "id": "junyeon-moment-07",
    "person": "junyeon",
    "chapter": 3,
    "visit": 1,
    "title": "문틈의 박자",
    "location": "band",
    "lines": [
      {
        "speaker": "narrator",
        "text": "합주가 끝난 문 앞에서 준연의 손가락이 가방 끈을 두드리고 있었다."
      },
      {
        "speaker": "junyeon",
        "text": "마지막 부분, 아직 귀에 남아. 좀 천천히 치던 데 있잖아."
      },
      {
        "speaker": "narrator",
        "text": "나는 멜로디를 낮게 흥얼거렸다. 준연이 손끝으로 박자를 맞췄다."
      }
    ],
    "bridge": "합주실 문이 닫힌 뒤 남은 정리를 하러 교실로 돌아오자 준연이 가방 끈에서 손가락을 떼고 내일 이야기를 꺼냈다."
  },
  {
    "id": "junyeon-moment-08",
    "person": "junyeon",
    "chapter": 3,
    "visit": 2,
    "title": "접힌 자국",
    "location": "art",
    "lines": [
      {
        "speaker": "narrator",
        "text": "한 번 접힌 종이는 쉽게 펴지지 않았다. 준연은 자를 내려놓았다."
      },
      {
        "speaker": "junyeon",
        "text": "세게 누르면 찢어질 것 같아. 그냥 이 자국대로 다른 걸 접어 볼까."
      },
      {
        "speaker": "narrator",
        "text": "우리는 종이를 반대로 돌렸다. 같은 자국이 이번에는 접을 선이 됐다."
      }
    ],
    "bridge": "연습하던 종이를 미술실에 두고 교실로 돌아온 준연은 책 사이에 따로 끼워 둔 찢어진 초대장을 꺼냈다."
  },
  {
    "id": "junyeon-moment-09",
    "person": "junyeon",
    "chapter": 4,
    "visit": 1,
    "title": "낙엽 하나",
    "location": "walk",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연은 길 위의 잎 하나를 집어 들고 한동안 말이 없었다."
      },
      {
        "speaker": "junyeon",
        "text": "이건 떨어진 지 얼마 안 됐나 봐. 아직 색이 진해."
      },
      {
        "speaker": "narrator",
        "text": "나는 바로 대답하지 않고 나란히 섰다. 그녀가 잎을 내려놓은 뒤 다시 걸었다."
      }
    ],
    "bridge": "짧은 산책을 마치고 교실에 돌아온 준연이 책상 위 수정 문서를 내 쪽에서도 보이게 돌려놓았다."
  },
  {
    "id": "junyeon-moment-10",
    "person": "junyeon",
    "chapter": 4,
    "visit": 2,
    "title": "저장하기 전",
    "location": "computer",
    "lines": [
      {
        "speaker": "narrator",
        "text": "준연은 파일 창을 열어 놓고 옆 의자를 바라봤다."
      },
      {
        "speaker": "junyeon",
        "text": "보내기 전에 한 번만 같이 읽어 줘. 내가 빠뜨린 게 있을 수도 있으니까."
      },
      {
        "speaker": "narrator",
        "text": "나는 의자를 가까이 옮겼다. 화면을 넘기는 속도는 둘이 함께 정했다."
      }
    ],
    "bridge": "함께 읽은 글을 보낸 뒤 다음 쉬는 시간 교실에서 만난 준연은 휴대폰을 책상 위에 엎어 두고 있었다."
  }
];

const byScene=new Map(illustrationMoments.map(moment=>[
 'hangout-'+moment.person+'-'+(moment.chapter+1)+'-v'+moment.visit,moment
]));
export function momentForScene(sceneId:string):IllustrationMoment|undefined{return byScene.get(sceneId);}

/** Opt-in at encounter ENTRY only. Old saves keep their exact dialogue cursor. */
export function withIllustratedMoment(scene:RScene,state:RState):RScene{
 const moment=momentForScene(scene.id);
 if(!moment||!state.flags.includes('art:moment:'+scene.id))return scene;
 const prelude:RLine[]=moment.lines.map(line=>({
  ...line,text:line.text.replaceAll('{name}',state.name),art:moment.id,location:moment.location
 }));
 // A marker with no art ends this CG even when both portions share a room.
 // Keep the original title/location/choices/memory and all original CG beats.
 const transition:RLine={
  speaker:'narrator',location:scene.location,
  text:moment.bridge
 };
 return {...scene,lines:[...prelude,transition,...scene.lines]};
}
